// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using SnapraidDeamonApi.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SnapraidDeamonApi.Snapraid.V1.Schedule
{
    /// <summary>
    /// Builds and executes requests for operations under \snapraid\v1\schedule
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ScheduleRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Snapraid.V1.Schedule.ScheduleRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ScheduleRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/snapraid/v1/schedule", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Snapraid.V1.Schedule.ScheduleRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ScheduleRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/snapraid/v1/schedule", rawUrl)
        {
        }
        /// <summary>
        /// Queues one or more SnapRAID CLI commands to be executed sequentially in a single session.Execution Logic: - Commands are executed in the exact order provided in the &apos;tasks&apos; array. - If a command fails, all subsequent tasks in the queue are automatically  cancelled to prevent operating on inconsistent data.- Exception: The &apos;report&apos; and &apos;down&apos; commands are treated as finalizers.  If they are present in the sequence, they will be executed regardless  of the success or failure of preceding commands.Clients should monitor /state endpoint to track the progress of the currently active command and the overall queue status via pulse counters.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.Schedule.SchedulePostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::SnapraidDeamonApi.Models.Schedule400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Schedule405Error">When receiving a 405 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Schedule500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Schedule.SchedulePostResponse?> PostAsSchedulePostResponseAsync(global::SnapraidDeamonApi.Snapraid.V1.Schedule.SchedulePostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Schedule.SchedulePostResponse> PostAsSchedulePostResponseAsync(global::SnapraidDeamonApi.Snapraid.V1.Schedule.SchedulePostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::SnapraidDeamonApi.Models.Schedule400Error.CreateFromDiscriminatorValue },
                { "405", global::SnapraidDeamonApi.Models.Schedule405Error.CreateFromDiscriminatorValue },
                { "500", global::SnapraidDeamonApi.Models.Schedule500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::SnapraidDeamonApi.Snapraid.V1.Schedule.SchedulePostResponse>(requestInfo, global::SnapraidDeamonApi.Snapraid.V1.Schedule.SchedulePostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Queues one or more SnapRAID CLI commands to be executed sequentially in a single session.Execution Logic: - Commands are executed in the exact order provided in the &apos;tasks&apos; array. - If a command fails, all subsequent tasks in the queue are automatically  cancelled to prevent operating on inconsistent data.- Exception: The &apos;report&apos; and &apos;down&apos; commands are treated as finalizers.  If they are present in the sequence, they will be executed regardless  of the success or failure of preceding commands.Clients should monitor /state endpoint to track the progress of the currently active command and the overall queue status via pulse counters.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.Schedule.ScheduleResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::SnapraidDeamonApi.Models.Schedule400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Schedule405Error">When receiving a 405 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Schedule500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsSchedulePostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Schedule.ScheduleResponse?> PostAsync(global::SnapraidDeamonApi.Snapraid.V1.Schedule.SchedulePostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Schedule.ScheduleResponse> PostAsync(global::SnapraidDeamonApi.Snapraid.V1.Schedule.SchedulePostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::SnapraidDeamonApi.Models.Schedule400Error.CreateFromDiscriminatorValue },
                { "405", global::SnapraidDeamonApi.Models.Schedule405Error.CreateFromDiscriminatorValue },
                { "500", global::SnapraidDeamonApi.Models.Schedule500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::SnapraidDeamonApi.Snapraid.V1.Schedule.ScheduleResponse>(requestInfo, global::SnapraidDeamonApi.Snapraid.V1.Schedule.ScheduleResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Queues one or more SnapRAID CLI commands to be executed sequentially in a single session.Execution Logic: - Commands are executed in the exact order provided in the &apos;tasks&apos; array. - If a command fails, all subsequent tasks in the queue are automatically  cancelled to prevent operating on inconsistent data.- Exception: The &apos;report&apos; and &apos;down&apos; commands are treated as finalizers.  If they are present in the sequence, they will be executed regardless  of the success or failure of preceding commands.Clients should monitor /state endpoint to track the progress of the currently active command and the overall queue status via pulse counters.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::SnapraidDeamonApi.Snapraid.V1.Schedule.SchedulePostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::SnapraidDeamonApi.Snapraid.V1.Schedule.SchedulePostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.Schedule.ScheduleRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::SnapraidDeamonApi.Snapraid.V1.Schedule.ScheduleRequestBuilder WithUrl(string rawUrl)
        {
            return new global::SnapraidDeamonApi.Snapraid.V1.Schedule.ScheduleRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ScheduleRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
