// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using SnapraidDeamonApi.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SnapraidDeamonApi.Snapraid.V1.Undelete
{
    /// <summary>
    /// Builds and executes requests for operations under \snapraid\v1\undelete
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UndeleteRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Snapraid.V1.Undelete.UndeleteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UndeleteRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/snapraid/v1/undelete", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Snapraid.V1.Undelete.UndeleteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UndeleteRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/snapraid/v1/undelete", rawUrl)
        {
        }
        /// <summary>
        /// Initiates a restoration process for files that are present in the parity but missing from the physical data disks by executing &apos;up&apos;, followed by &apos;fix -m&apos;. The process is concluded by a &apos;report&apos; task to notify the result.The &apos;-m&apos; flag ensures that only missing files are reconstructed. Existing files are never overwritten or modified.The request accepts an optional list of filters to narrow the scope of restoration to specific directories or file patterns. If no filter is provided, the daemon attempts to recover all missing files across the entire array.This is an asynchronous operation. Monitor progress via the /activity endpoint.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.Undelete.UndeletePostResponse"/></returns>
        /// <param name="body">Optional configuration for the task.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::SnapraidDeamonApi.Models.Undelete400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Undelete405Error">When receiving a 405 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Undelete500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Undelete.UndeletePostResponse?> PostAsUndeletePostResponseAsync(global::SnapraidDeamonApi.Models.CommandRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Undelete.UndeletePostResponse> PostAsUndeletePostResponseAsync(global::SnapraidDeamonApi.Models.CommandRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::SnapraidDeamonApi.Models.Undelete400Error.CreateFromDiscriminatorValue },
                { "405", global::SnapraidDeamonApi.Models.Undelete405Error.CreateFromDiscriminatorValue },
                { "500", global::SnapraidDeamonApi.Models.Undelete500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::SnapraidDeamonApi.Snapraid.V1.Undelete.UndeletePostResponse>(requestInfo, global::SnapraidDeamonApi.Snapraid.V1.Undelete.UndeletePostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Initiates a restoration process for files that are present in the parity but missing from the physical data disks by executing &apos;up&apos;, followed by &apos;fix -m&apos;. The process is concluded by a &apos;report&apos; task to notify the result.The &apos;-m&apos; flag ensures that only missing files are reconstructed. Existing files are never overwritten or modified.The request accepts an optional list of filters to narrow the scope of restoration to specific directories or file patterns. If no filter is provided, the daemon attempts to recover all missing files across the entire array.This is an asynchronous operation. Monitor progress via the /activity endpoint.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.Undelete.UndeleteResponse"/></returns>
        /// <param name="body">Optional configuration for the task.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::SnapraidDeamonApi.Models.Undelete400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Undelete405Error">When receiving a 405 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Undelete500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsUndeletePostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Undelete.UndeleteResponse?> PostAsync(global::SnapraidDeamonApi.Models.CommandRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Undelete.UndeleteResponse> PostAsync(global::SnapraidDeamonApi.Models.CommandRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::SnapraidDeamonApi.Models.Undelete400Error.CreateFromDiscriminatorValue },
                { "405", global::SnapraidDeamonApi.Models.Undelete405Error.CreateFromDiscriminatorValue },
                { "500", global::SnapraidDeamonApi.Models.Undelete500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::SnapraidDeamonApi.Snapraid.V1.Undelete.UndeleteResponse>(requestInfo, global::SnapraidDeamonApi.Snapraid.V1.Undelete.UndeleteResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Initiates a restoration process for files that are present in the parity but missing from the physical data disks by executing &apos;up&apos;, followed by &apos;fix -m&apos;. The process is concluded by a &apos;report&apos; task to notify the result.The &apos;-m&apos; flag ensures that only missing files are reconstructed. Existing files are never overwritten or modified.The request accepts an optional list of filters to narrow the scope of restoration to specific directories or file patterns. If no filter is provided, the daemon attempts to recover all missing files across the entire array.This is an asynchronous operation. Monitor progress via the /activity endpoint.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Optional configuration for the task.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::SnapraidDeamonApi.Models.CommandRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::SnapraidDeamonApi.Models.CommandRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.Undelete.UndeleteRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::SnapraidDeamonApi.Snapraid.V1.Undelete.UndeleteRequestBuilder WithUrl(string rawUrl)
        {
            return new global::SnapraidDeamonApi.Snapraid.V1.Undelete.UndeleteRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UndeleteRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
