// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using SnapraidDeamonApi.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SnapraidDeamonApi.Snapraid.V1.Heal
{
    /// <summary>
    /// Builds and executes requests for operations under \snapraid\v1\heal
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HealRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Snapraid.V1.Heal.HealRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HealRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/snapraid/v1/heal", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Snapraid.V1.Heal.HealRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HealRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/snapraid/v1/heal", rawUrl)
        {
        }
        /// <summary>
        /// Initiates a recovery operation to resolve data corruption by executing &apos;up&apos;, followed by &apos;fix -e&apos;, and followed by &apos;scrub -p bad&apos;. The process is concluded by a &apos;report&apos; task to notify the result.The &apos;-e fix&apos; command utilizes parity data to reconstruct blocks marked as having silent errors (checksum mismatches) and restores the physical files on the data disks.The &apos;-p bad scrub&apos; command performs a targeted re-verification of known &apos;bad&apos; blocks. If the fix was successful, it clears the error entries from the content file, resetting the health status of the array.This is an asynchronous operation. Monitor progress via the /activity endpoint.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.Heal.HealPostResponse"/></returns>
        /// <param name="body">Optional configuration for the task.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::SnapraidDeamonApi.Models.Heal400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Heal405Error">When receiving a 405 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Heal500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Heal.HealPostResponse?> PostAsHealPostResponseAsync(global::SnapraidDeamonApi.Models.CommandRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Heal.HealPostResponse> PostAsHealPostResponseAsync(global::SnapraidDeamonApi.Models.CommandRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::SnapraidDeamonApi.Models.Heal400Error.CreateFromDiscriminatorValue },
                { "405", global::SnapraidDeamonApi.Models.Heal405Error.CreateFromDiscriminatorValue },
                { "500", global::SnapraidDeamonApi.Models.Heal500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::SnapraidDeamonApi.Snapraid.V1.Heal.HealPostResponse>(requestInfo, global::SnapraidDeamonApi.Snapraid.V1.Heal.HealPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Initiates a recovery operation to resolve data corruption by executing &apos;up&apos;, followed by &apos;fix -e&apos;, and followed by &apos;scrub -p bad&apos;. The process is concluded by a &apos;report&apos; task to notify the result.The &apos;-e fix&apos; command utilizes parity data to reconstruct blocks marked as having silent errors (checksum mismatches) and restores the physical files on the data disks.The &apos;-p bad scrub&apos; command performs a targeted re-verification of known &apos;bad&apos; blocks. If the fix was successful, it clears the error entries from the content file, resetting the health status of the array.This is an asynchronous operation. Monitor progress via the /activity endpoint.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.Heal.HealResponse"/></returns>
        /// <param name="body">Optional configuration for the task.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::SnapraidDeamonApi.Models.Heal400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Heal405Error">When receiving a 405 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Heal500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsHealPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Heal.HealResponse?> PostAsync(global::SnapraidDeamonApi.Models.CommandRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Heal.HealResponse> PostAsync(global::SnapraidDeamonApi.Models.CommandRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::SnapraidDeamonApi.Models.Heal400Error.CreateFromDiscriminatorValue },
                { "405", global::SnapraidDeamonApi.Models.Heal405Error.CreateFromDiscriminatorValue },
                { "500", global::SnapraidDeamonApi.Models.Heal500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::SnapraidDeamonApi.Snapraid.V1.Heal.HealResponse>(requestInfo, global::SnapraidDeamonApi.Snapraid.V1.Heal.HealResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Initiates a recovery operation to resolve data corruption by executing &apos;up&apos;, followed by &apos;fix -e&apos;, and followed by &apos;scrub -p bad&apos;. The process is concluded by a &apos;report&apos; task to notify the result.The &apos;-e fix&apos; command utilizes parity data to reconstruct blocks marked as having silent errors (checksum mismatches) and restores the physical files on the data disks.The &apos;-p bad scrub&apos; command performs a targeted re-verification of known &apos;bad&apos; blocks. If the fix was successful, it clears the error entries from the content file, resetting the health status of the array.This is an asynchronous operation. Monitor progress via the /activity endpoint.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Optional configuration for the task.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::SnapraidDeamonApi.Models.CommandRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::SnapraidDeamonApi.Models.CommandRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.Heal.HealRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::SnapraidDeamonApi.Snapraid.V1.Heal.HealRequestBuilder WithUrl(string rawUrl)
        {
            return new global::SnapraidDeamonApi.Snapraid.V1.Heal.HealRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class HealRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
