// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using SnapraidDeamonApi.Snapraid.V1.Activity;
using SnapraidDeamonApi.Snapraid.V1.ArrayNamespace;
using SnapraidDeamonApi.Snapraid.V1.Config;
using SnapraidDeamonApi.Snapraid.V1.Disks;
using SnapraidDeamonApi.Snapraid.V1.Heal;
using SnapraidDeamonApi.Snapraid.V1.Hold_off;
using SnapraidDeamonApi.Snapraid.V1.Maintenance;
using SnapraidDeamonApi.Snapraid.V1.Refresh;
using SnapraidDeamonApi.Snapraid.V1.Schedule;
using SnapraidDeamonApi.Snapraid.V1.State;
using SnapraidDeamonApi.Snapraid.V1.Stop;
using SnapraidDeamonApi.Snapraid.V1.Suspend_idle;
using SnapraidDeamonApi.Snapraid.V1.System;
using SnapraidDeamonApi.Snapraid.V1.Tasks;
using SnapraidDeamonApi.Snapraid.V1.Undelete;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace SnapraidDeamonApi.Snapraid.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \snapraid\v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The activity property</summary>
        public global::SnapraidDeamonApi.Snapraid.V1.Activity.ActivityRequestBuilder Activity
        {
            get => new global::SnapraidDeamonApi.Snapraid.V1.Activity.ActivityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The array property</summary>
        public global::SnapraidDeamonApi.Snapraid.V1.ArrayNamespace.ArrayRequestBuilder Array
        {
            get => new global::SnapraidDeamonApi.Snapraid.V1.ArrayNamespace.ArrayRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The config property</summary>
        public global::SnapraidDeamonApi.Snapraid.V1.Config.ConfigRequestBuilder Config
        {
            get => new global::SnapraidDeamonApi.Snapraid.V1.Config.ConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The disks property</summary>
        public global::SnapraidDeamonApi.Snapraid.V1.Disks.DisksRequestBuilder Disks
        {
            get => new global::SnapraidDeamonApi.Snapraid.V1.Disks.DisksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The heal property</summary>
        public global::SnapraidDeamonApi.Snapraid.V1.Heal.HealRequestBuilder Heal
        {
            get => new global::SnapraidDeamonApi.Snapraid.V1.Heal.HealRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The hold_off property</summary>
        public global::SnapraidDeamonApi.Snapraid.V1.Hold_off.Hold_offRequestBuilder Hold_off
        {
            get => new global::SnapraidDeamonApi.Snapraid.V1.Hold_off.Hold_offRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The maintenance property</summary>
        public global::SnapraidDeamonApi.Snapraid.V1.Maintenance.MaintenanceRequestBuilder Maintenance
        {
            get => new global::SnapraidDeamonApi.Snapraid.V1.Maintenance.MaintenanceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The refresh property</summary>
        public global::SnapraidDeamonApi.Snapraid.V1.Refresh.RefreshRequestBuilder Refresh
        {
            get => new global::SnapraidDeamonApi.Snapraid.V1.Refresh.RefreshRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The schedule property</summary>
        public global::SnapraidDeamonApi.Snapraid.V1.Schedule.ScheduleRequestBuilder Schedule
        {
            get => new global::SnapraidDeamonApi.Snapraid.V1.Schedule.ScheduleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The state property</summary>
        public global::SnapraidDeamonApi.Snapraid.V1.State.StateRequestBuilder State
        {
            get => new global::SnapraidDeamonApi.Snapraid.V1.State.StateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stop property</summary>
        public global::SnapraidDeamonApi.Snapraid.V1.Stop.StopRequestBuilder Stop
        {
            get => new global::SnapraidDeamonApi.Snapraid.V1.Stop.StopRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The suspend_idle property</summary>
        public global::SnapraidDeamonApi.Snapraid.V1.Suspend_idle.Suspend_idleRequestBuilder Suspend_idle
        {
            get => new global::SnapraidDeamonApi.Snapraid.V1.Suspend_idle.Suspend_idleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The system property</summary>
        public global::SnapraidDeamonApi.Snapraid.V1.System.SystemRequestBuilder System
        {
            get => new global::SnapraidDeamonApi.Snapraid.V1.System.SystemRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tasks property</summary>
        public global::SnapraidDeamonApi.Snapraid.V1.Tasks.TasksRequestBuilder Tasks
        {
            get => new global::SnapraidDeamonApi.Snapraid.V1.Tasks.TasksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The undelete property</summary>
        public global::SnapraidDeamonApi.Snapraid.V1.Undelete.UndeleteRequestBuilder Undelete
        {
            get => new global::SnapraidDeamonApi.Snapraid.V1.Undelete.UndeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Snapraid.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/snapraid/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Snapraid.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/snapraid/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
