// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using SnapraidDeamonApi.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SnapraidDeamonApi.Snapraid.V1.Disks
{
    /// <summary>
    /// Builds and executes requests for operations under \snapraid\v1\disks
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DisksRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Snapraid.V1.Disks.DisksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DisksRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/snapraid/v1/disks", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Snapraid.V1.Disks.DisksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DisksRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/snapraid/v1/disks", rawUrl)
        {
        }
        /// <summary>
        /// Returns a comprehensive report of all data and parity disks managed by the daemon.This is a passive operation that retrieves the most recent information stored in memory. Calling this endpoint will NOT trigger a physical disk probe or spin up any standby disks.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.Disks.DisksGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::SnapraidDeamonApi.Models.Disks400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Disks405Error">When receiving a 405 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Disks.DisksGetResponse?> GetAsDisksGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Disks.DisksGetResponse> GetAsDisksGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::SnapraidDeamonApi.Models.Disks400Error.CreateFromDiscriminatorValue },
                { "405", global::SnapraidDeamonApi.Models.Disks405Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::SnapraidDeamonApi.Snapraid.V1.Disks.DisksGetResponse>(requestInfo, global::SnapraidDeamonApi.Snapraid.V1.Disks.DisksGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a comprehensive report of all data and parity disks managed by the daemon.This is a passive operation that retrieves the most recent information stored in memory. Calling this endpoint will NOT trigger a physical disk probe or spin up any standby disks.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.Disks.DisksResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::SnapraidDeamonApi.Models.Disks400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Disks405Error">When receiving a 405 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsDisksGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Disks.DisksResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Disks.DisksResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::SnapraidDeamonApi.Models.Disks400Error.CreateFromDiscriminatorValue },
                { "405", global::SnapraidDeamonApi.Models.Disks405Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::SnapraidDeamonApi.Snapraid.V1.Disks.DisksResponse>(requestInfo, global::SnapraidDeamonApi.Snapraid.V1.Disks.DisksResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a comprehensive report of all data and parity disks managed by the daemon.This is a passive operation that retrieves the most recent information stored in memory. Calling this endpoint will NOT trigger a physical disk probe or spin up any standby disks.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.Disks.DisksRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::SnapraidDeamonApi.Snapraid.V1.Disks.DisksRequestBuilder WithUrl(string rawUrl)
        {
            return new global::SnapraidDeamonApi.Snapraid.V1.Disks.DisksRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DisksRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
