// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using SnapraidDeamonApi.Models;
using System.Collections.Generic;
using System.IO;
using System;
namespace SnapraidDeamonApi.Snapraid.V1.Disks
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DisksGetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Ordered list of data disks (d1, d2, ...)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SnapraidDeamonApi.Models.Disk>? DataDisks { get; set; }
#nullable restore
#else
        public List<global::SnapraidDeamonApi.Models.Disk> DataDisks { get; set; }
#endif
        /// <summary>Ordered list of extra disks (boot, data, ...)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SnapraidDeamonApi.Models.Disk>? ExtraDisks { get; set; }
#nullable restore
#else
        public List<global::SnapraidDeamonApi.Models.Disk> ExtraDisks { get; set; }
#endif
        /// <summary>Ordered list of parity disks (parity, 2-parity, ...)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SnapraidDeamonApi.Models.Disk>? ParityDisks { get; set; }
#nullable restore
#else
        public List<global::SnapraidDeamonApi.Models.Disk> ParityDisks { get; set; }
#endif
        /// <summary>A collection of monotonic sequence counters used for state change detection. Each field corresponds directly to the API entry point of the same name.If a specific pulse field increments, the corresponding endpoint will potentially return different data. Clients should use these counters to trigger selective cache invalidation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SnapraidDeamonApi.Models.Pulse? Pulse { get; set; }
#nullable restore
#else
        public global::SnapraidDeamonApi.Models.Pulse Pulse { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Snapraid.V1.Disks.DisksGetResponse"/> and sets the default values.
        /// </summary>
        public DisksGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.Disks.DisksGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SnapraidDeamonApi.Snapraid.V1.Disks.DisksGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SnapraidDeamonApi.Snapraid.V1.Disks.DisksGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "data_disks", n => { DataDisks = n.GetCollectionOfObjectValues<global::SnapraidDeamonApi.Models.Disk>(global::SnapraidDeamonApi.Models.Disk.CreateFromDiscriminatorValue)?.AsList(); } },
                { "extra_disks", n => { ExtraDisks = n.GetCollectionOfObjectValues<global::SnapraidDeamonApi.Models.Disk>(global::SnapraidDeamonApi.Models.Disk.CreateFromDiscriminatorValue)?.AsList(); } },
                { "parity_disks", n => { ParityDisks = n.GetCollectionOfObjectValues<global::SnapraidDeamonApi.Models.Disk>(global::SnapraidDeamonApi.Models.Disk.CreateFromDiscriminatorValue)?.AsList(); } },
                { "pulse", n => { Pulse = n.GetObjectValue<global::SnapraidDeamonApi.Models.Pulse>(global::SnapraidDeamonApi.Models.Pulse.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::SnapraidDeamonApi.Models.Disk>("data_disks", DataDisks);
            writer.WriteCollectionOfObjectValues<global::SnapraidDeamonApi.Models.Disk>("extra_disks", ExtraDisks);
            writer.WriteCollectionOfObjectValues<global::SnapraidDeamonApi.Models.Disk>("parity_disks", ParityDisks);
            writer.WriteObjectValue<global::SnapraidDeamonApi.Models.Pulse>("pulse", Pulse);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
