// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SnapraidDeamonApi.Snapraid.V1.ArrayNamespace
{
    /// <summary>
    /// Builds and executes requests for operations under \snapraid\v1\array
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ArrayRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Snapraid.V1.ArrayNamespace.ArrayRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ArrayRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/snapraid/v1/array", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Snapraid.V1.ArrayNamespace.ArrayRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ArrayRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/snapraid/v1/array", rawUrl)
        {
        }
        /// <summary>
        /// Returns the top-level logical state of the array. This includes software versioning, SnapRAID CLI block configuration, and the timestamps of the most recent maintenance tasks.The &apos;diff&apos; statistics represent the drift between the actual files on disk and the parity information, as recorded during the last array check.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.ArrayNamespace.ArrayGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.ArrayNamespace.ArrayGetResponse?> GetAsArrayGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.ArrayNamespace.ArrayGetResponse> GetAsArrayGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::SnapraidDeamonApi.Snapraid.V1.ArrayNamespace.ArrayGetResponse>(requestInfo, global::SnapraidDeamonApi.Snapraid.V1.ArrayNamespace.ArrayGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the top-level logical state of the array. This includes software versioning, SnapRAID CLI block configuration, and the timestamps of the most recent maintenance tasks.The &apos;diff&apos; statistics represent the drift between the actual files on disk and the parity information, as recorded during the last array check.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.ArrayNamespace.ArrayResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsArrayGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.ArrayNamespace.ArrayResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.ArrayNamespace.ArrayResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::SnapraidDeamonApi.Snapraid.V1.ArrayNamespace.ArrayResponse>(requestInfo, global::SnapraidDeamonApi.Snapraid.V1.ArrayNamespace.ArrayResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the top-level logical state of the array. This includes software versioning, SnapRAID CLI block configuration, and the timestamps of the most recent maintenance tasks.The &apos;diff&apos; statistics represent the drift between the actual files on disk and the parity information, as recorded during the last array check.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.ArrayNamespace.ArrayRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::SnapraidDeamonApi.Snapraid.V1.ArrayNamespace.ArrayRequestBuilder WithUrl(string rawUrl)
        {
            return new global::SnapraidDeamonApi.Snapraid.V1.ArrayNamespace.ArrayRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ArrayRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
