// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using SnapraidDeamonApi.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SnapraidDeamonApi.Snapraid.V1.Maintenance
{
    /// <summary>
    /// Builds and executes requests for operations under \snapraid\v1\maintenance
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MaintenanceRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Snapraid.V1.Maintenance.MaintenanceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MaintenanceRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/snapraid/v1/maintenance", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Snapraid.V1.Maintenance.MaintenanceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MaintenanceRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/snapraid/v1/maintenance", rawUrl)
        {
        }
        /// <summary>
        /// Initiates the automated maintenance workflow, executing &apos;up&apos;, &apos;sync&apos;, and &apos;scrub&apos;. The process is concluded by a &apos;report&apos; task to notify the result.This operation is subject to all safety thresholds defined in the daemon configuration, specifically &apos;sync_threshold_deletes&apos; and &apos;sync_threshold_updates&apos;.If the &apos;sync&apos; phase exceeds the delete threshold, the daemon will suspend the &apos;sync&apos; task to prevent accidental data loss. Regardless, the &apos;scrub&apos; phase is not bypassed.This is an asynchronous operation. Monitor progress via the /activity endpoint.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.Maintenance.MaintenancePostResponse"/></returns>
        /// <param name="body">Optional configuration for the task.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::SnapraidDeamonApi.Models.Maintenance400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Maintenance405Error">When receiving a 405 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Maintenance500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Maintenance.MaintenancePostResponse?> PostAsMaintenancePostResponseAsync(global::SnapraidDeamonApi.Models.CommandRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Maintenance.MaintenancePostResponse> PostAsMaintenancePostResponseAsync(global::SnapraidDeamonApi.Models.CommandRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::SnapraidDeamonApi.Models.Maintenance400Error.CreateFromDiscriminatorValue },
                { "405", global::SnapraidDeamonApi.Models.Maintenance405Error.CreateFromDiscriminatorValue },
                { "500", global::SnapraidDeamonApi.Models.Maintenance500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::SnapraidDeamonApi.Snapraid.V1.Maintenance.MaintenancePostResponse>(requestInfo, global::SnapraidDeamonApi.Snapraid.V1.Maintenance.MaintenancePostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Initiates the automated maintenance workflow, executing &apos;up&apos;, &apos;sync&apos;, and &apos;scrub&apos;. The process is concluded by a &apos;report&apos; task to notify the result.This operation is subject to all safety thresholds defined in the daemon configuration, specifically &apos;sync_threshold_deletes&apos; and &apos;sync_threshold_updates&apos;.If the &apos;sync&apos; phase exceeds the delete threshold, the daemon will suspend the &apos;sync&apos; task to prevent accidental data loss. Regardless, the &apos;scrub&apos; phase is not bypassed.This is an asynchronous operation. Monitor progress via the /activity endpoint.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.Maintenance.MaintenanceResponse"/></returns>
        /// <param name="body">Optional configuration for the task.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::SnapraidDeamonApi.Models.Maintenance400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Maintenance405Error">When receiving a 405 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Maintenance500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsMaintenancePostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Maintenance.MaintenanceResponse?> PostAsync(global::SnapraidDeamonApi.Models.CommandRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Maintenance.MaintenanceResponse> PostAsync(global::SnapraidDeamonApi.Models.CommandRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::SnapraidDeamonApi.Models.Maintenance400Error.CreateFromDiscriminatorValue },
                { "405", global::SnapraidDeamonApi.Models.Maintenance405Error.CreateFromDiscriminatorValue },
                { "500", global::SnapraidDeamonApi.Models.Maintenance500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::SnapraidDeamonApi.Snapraid.V1.Maintenance.MaintenanceResponse>(requestInfo, global::SnapraidDeamonApi.Snapraid.V1.Maintenance.MaintenanceResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Initiates the automated maintenance workflow, executing &apos;up&apos;, &apos;sync&apos;, and &apos;scrub&apos;. The process is concluded by a &apos;report&apos; task to notify the result.This operation is subject to all safety thresholds defined in the daemon configuration, specifically &apos;sync_threshold_deletes&apos; and &apos;sync_threshold_updates&apos;.If the &apos;sync&apos; phase exceeds the delete threshold, the daemon will suspend the &apos;sync&apos; task to prevent accidental data loss. Regardless, the &apos;scrub&apos; phase is not bypassed.This is an asynchronous operation. Monitor progress via the /activity endpoint.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Optional configuration for the task.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::SnapraidDeamonApi.Models.CommandRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::SnapraidDeamonApi.Models.CommandRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.Maintenance.MaintenanceRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::SnapraidDeamonApi.Snapraid.V1.Maintenance.MaintenanceRequestBuilder WithUrl(string rawUrl)
        {
            return new global::SnapraidDeamonApi.Snapraid.V1.Maintenance.MaintenanceRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MaintenanceRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
