// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using SnapraidDeamonApi.Models;
using System.Collections.Generic;
using System.IO;
using System;
namespace SnapraidDeamonApi.Snapraid.V1.State
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class StateGetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The name of the currently running command. Omitted from the response if the daemon is idle.</summary>
        public global::SnapraidDeamonApi.Snapraid.V1.State.StateGetResponse_active_command? ActiveCommand { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Estimated seconds remaining until the active command completes.This field is omitted if the daemon is idle, or if an estimate is not yet available/supported for the current task.</summary>
        public int? EtaSeconds { get; set; }
        /// <summary>The aggregate health of the entire array.* passed: All member devices are nominal, and no data  inconsistencies are detected.* corrupt: This is triggered by the presence of silent  data errors, specifically if the &apos;blocks_bad&apos; counter  is greater than zero.* prefail: A critical state indicating that one or more  underlying devices have encountered I/O failures, or a  SMART prefail condition.* failing: A critical state indicating that one or more  underlying devices have encountered a SMART failing  condition.* pending: The aggregate health has not yet been  determined.</summary>
        public global::SnapraidDeamonApi.Snapraid.V1.State.StateGetResponse_health? Health { get; set; }
        /// <summary>A human-readable string explaining the current health state. This provides the specific cause when health is &apos;corrupt&apos;, &apos;prefail&apos; or &apos;failing&apos; (e.g., &quot;Disk &apos;d1&apos; reporting SMART errors&quot;). This field is omitted if the array is healthy.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HealthReason { get; set; }
#nullable restore
#else
        public string HealthReason { get; set; }
#endif
        /// <summary>The next command scheduled in the current execution sequence. This field is present when the daemon is running an automated workflow and there are pending steps remaining in the queue. If no subsequent task is queued, this field is omitted.</summary>
        public global::SnapraidDeamonApi.Snapraid.V1.State.StateGetResponse_next_command? NextCommand { get; set; }
        /// <summary>The completion percentage of the active command (0-100).This field is omitted if the daemon is idle, or if the currently running command does not provide granular progress telemetry (e.g., &apos;up&apos; or &apos;smart&apos;).</summary>
        public int? Progress { get; set; }
        /// <summary>A collection of monotonic sequence counters used for state change detection. Each field corresponds directly to the API entry point of the same name.If a specific pulse field increments, the corresponding endpoint will potentially return different data. Clients should use these counters to trigger selective cache invalidation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SnapraidDeamonApi.Models.Pulse? Pulse { get; set; }
#nullable restore
#else
        public global::SnapraidDeamonApi.Models.Pulse Pulse { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Snapraid.V1.State.StateGetResponse"/> and sets the default values.
        /// </summary>
        public StateGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.State.StateGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SnapraidDeamonApi.Snapraid.V1.State.StateGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SnapraidDeamonApi.Snapraid.V1.State.StateGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active_command", n => { ActiveCommand = n.GetEnumValue<global::SnapraidDeamonApi.Snapraid.V1.State.StateGetResponse_active_command>(); } },
                { "eta_seconds", n => { EtaSeconds = n.GetIntValue(); } },
                { "health", n => { Health = n.GetEnumValue<global::SnapraidDeamonApi.Snapraid.V1.State.StateGetResponse_health>(); } },
                { "health_reason", n => { HealthReason = n.GetStringValue(); } },
                { "next_command", n => { NextCommand = n.GetEnumValue<global::SnapraidDeamonApi.Snapraid.V1.State.StateGetResponse_next_command>(); } },
                { "progress", n => { Progress = n.GetIntValue(); } },
                { "pulse", n => { Pulse = n.GetObjectValue<global::SnapraidDeamonApi.Models.Pulse>(global::SnapraidDeamonApi.Models.Pulse.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::SnapraidDeamonApi.Snapraid.V1.State.StateGetResponse_active_command>("active_command", ActiveCommand);
            writer.WriteIntValue("eta_seconds", EtaSeconds);
            writer.WriteEnumValue<global::SnapraidDeamonApi.Snapraid.V1.State.StateGetResponse_health>("health", Health);
            writer.WriteStringValue("health_reason", HealthReason);
            writer.WriteEnumValue<global::SnapraidDeamonApi.Snapraid.V1.State.StateGetResponse_next_command>("next_command", NextCommand);
            writer.WriteIntValue("progress", Progress);
            writer.WriteObjectValue<global::SnapraidDeamonApi.Models.Pulse>("pulse", Pulse);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
