// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SnapraidDeamonApi.Models
{
    /// <summary>
    /// Comprehensive state of array configuration, health metrics, and execution metadata.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ArrayObject : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The arithmetic sum of the Annual Failure Rates (AFR) for all disks in the array, representing the expected number of device failures per year.</summary>
        public double? AnnualFailureRate { get; set; }
        /// <summary>The count of blocks flagged as corrupted. These blocks require a &apos;fix&apos; operation to restore data integrity.</summary>
        public long? BlocksBad { get; set; }
        /// <summary>The total number of data blocks tracked in the content file. This value serves as the denominator for calculating the percentage of the array that is unsynced, unscrubbed, or bad.</summary>
        public long? BlocksCount { get; set; }
        /// <summary>Array block size in bytes (always power of 2).</summary>
        public int? BlockSizeBytes { get; set; }
        /// <summary>The count of blocks scheduled for a rehash. This occurs when upgrading the hash algorithm.</summary>
        public long? BlocksRehash { get; set; }
        /// <summary>The count of blocks that have never been scrubbed. Newly added files are reported as unscrubbed immediately following a successful sync until a scrub task is performed.</summary>
        public long? BlocksUnscrubbed { get; set; }
        /// <summary>The count of blocks that currently require a parity sync. These are typically present only after a sync task has been interrupted or failed to complete.</summary>
        public long? BlocksUnsynced { get; set; }
        /// <summary>Absolute path to the SnapRAID Daemon configuration file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DaemonConf { get; set; }
#nullable restore
#else
        public string DaemonConf { get; set; }
#endif
        /// <summary>The version of the SnapRAID Daemon currently running.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DaemonVersion { get; set; }
#nullable restore
#else
        public string DaemonVersion { get; set; }
#endif
        /// <summary>The total number of data disks currently registered and protected in the SnapRAID CLI configuration.</summary>
        public int? DataDisksCount { get; set; }
        /// <summary>The count of brand new files not present in the last sync.</summary>
        public long? DiffAdded { get; set; }
        /// <summary>The count of new files created by copying an existing protected file to a new path.</summary>
        public long? DiffCopied { get; set; }
        /// <summary>The count of files whose metadata and data match the current parity.</summary>
        public long? DiffEqual { get; set; }
        /// <summary>The count of files relocated to a new path or renamed but retaining the same inode.</summary>
        public long? DiffMoved { get; set; }
        /// <summary>The count of new files created by moving an existing protected file to a new path.</summary>
        public long? DiffRelocated { get; set; }
        /// <summary>The count of files that existed in the last sync but are now missing.</summary>
        public long? DiffRemoved { get; set; }
        /// <summary>The count of new files matching a parity entry by name/time/size but with a new inode (e.g., replaced from backup).</summary>
        public long? DiffRestored { get; set; }
        /// <summary>A collection of all changes detected in the array state obtained from the latest diff operation. These differences represent changes since the last sync.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SnapraidDeamonApi.Models.Diff>? Diffs { get; set; }
#nullable restore
#else
        public List<global::SnapraidDeamonApi.Models.Diff> Diffs { get; set; }
#endif
        /// <summary>The count of existing files where the timestamp or size has changed.</summary>
        public long? DiffUpdated { get; set; }
        /// <summary>Absolute path to the SnapRAID CLI configuration file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EngineConf { get; set; }
#nullable restore
#else
        public string EngineConf { get; set; }
#endif
        /// <summary>Absolute path to the primary SnapRAID CLI content file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EngineContent { get; set; }
#nullable restore
#else
        public string EngineContent { get; set; }
#endif
        /// <summary>The version of the underlying SnapRAID CLI binary.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EngineVersion { get; set; }
#nullable restore
#else
        public string EngineVersion { get; set; }
#endif
        /// <summary>The total number of extra disks currently registered in the SnapRAID CLI configuration.</summary>
        public int? ExtraDisksCount { get; set; }
        /// <summary>Statistical probability of at least one disk failure within a one-year period, calculated using a Poisson distribution model based on the aggregate Annual Failure Rate.</summary>
        public double? FailureProbability { get; set; }
        /// <summary>The number of files currently tracked within the content file across all data drives.</summary>
        public long? FilesCount { get; set; }
        /// <summary>A collection of all fixes done in the array. These fixes represent repair operation done since the last sync.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SnapraidDeamonApi.Models.Fix>? Fixes { get; set; }
#nullable restore
#else
        public List<global::SnapraidDeamonApi.Models.Fix> Fixes { get; set; }
#endif
        /// <summary>The count of files recovered in all the fix commands after the latest sync.</summary>
        public long? FixRecovered { get; set; }
        /// <summary>The count of files unrecoverable in all the fix commands after the latest sync.</summary>
        public long? FixUnrecoverable { get; set; }
        /// <summary>The free space in bytes of all the data disks (not counting parity disks).</summary>
        public long? FreeSpaceBytes { get; set; }
        /// <summary>The aggregate health of the entire array.* passed: All member devices are nominal, and no data  inconsistencies are detected.* corrupt: This is triggered by the presence of silent  data errors, specifically if the &apos;blocks_bad&apos; counter  is greater than zero.* prefail: A critical state indicating that one or more  underlying devices have encountered I/O failures, or a  SMART prefail condition.* failing: A critical state indicating that one or more  underlying devices have encountered a SMART failing  condition.* pending: The aggregate health has not yet been  determined.</summary>
        public global::SnapraidDeamonApi.Models.Array_health? Health { get; set; }
        /// <summary>Indicates if the next scheduled maintenance is currently flagged to be skipped. This value returns to false automatically after the skip event.</summary>
        public bool? HoldOff { get; set; }
        /// <summary>Identifier of the last successfully completed command.</summary>
        public global::SnapraidDeamonApi.Models.Array_last_command? LastCommand { get; set; }
        /// <summary>Local timestamp of the most recently concluded task.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastCommandAt { get; set; }
#nullable restore
#else
        public string LastCommandAt { get; set; }
#endif
        /// <summary>Local timestamp of the last array change analysis (&apos;diff&apos;).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastDiffAt { get; set; }
#nullable restore
#else
        public string LastDiffAt { get; set; }
#endif
        /// <summary>Local timestamp of the last array fix (&apos;fix&apos;).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastFixAt { get; set; }
#nullable restore
#else
        public string LastFixAt { get; set; }
#endif
        /// <summary>Local timestamp of the last data integrity verification (&apos;scrub&apos;).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastScrubAt { get; set; }
#nullable restore
#else
        public string LastScrubAt { get; set; }
#endif
        /// <summary>Local timestamp of the last parity synchronization (&apos;sync&apos;).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastSyncAt { get; set; }
#nullable restore
#else
        public string LastSyncAt { get; set; }
#endif
        /// <summary>The number of parity disks (redundancy levels) configured, defining how many simultaneous disk failures the array can survive.</summary>
        public int? ParityDisksCount { get; set; }
        /// <summary>The root object containing the time-seriesdata and the axis limits for the scrub report.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SnapraidDeamonApi.Models.ScrubHistory? ScrubHistory { get; set; }
#nullable restore
#else
        public global::SnapraidDeamonApi.Models.ScrubHistory ScrubHistory { get; set; }
#endif
        /// <summary>The size in bytes of all the data disks (not counting parity disks).</summary>
        public long? TotalSpaceBytes { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Models.ArrayObject"/> and sets the default values.
        /// </summary>
        public ArrayObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Models.ArrayObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SnapraidDeamonApi.Models.ArrayObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SnapraidDeamonApi.Models.ArrayObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "annual_failure_rate", n => { AnnualFailureRate = n.GetDoubleValue(); } },
                { "block_size_bytes", n => { BlockSizeBytes = n.GetIntValue(); } },
                { "blocks_bad", n => { BlocksBad = n.GetLongValue(); } },
                { "blocks_count", n => { BlocksCount = n.GetLongValue(); } },
                { "blocks_rehash", n => { BlocksRehash = n.GetLongValue(); } },
                { "blocks_unscrubbed", n => { BlocksUnscrubbed = n.GetLongValue(); } },
                { "blocks_unsynced", n => { BlocksUnsynced = n.GetLongValue(); } },
                { "daemon_conf", n => { DaemonConf = n.GetStringValue(); } },
                { "daemon_version", n => { DaemonVersion = n.GetStringValue(); } },
                { "data_disks_count", n => { DataDisksCount = n.GetIntValue(); } },
                { "diff_added", n => { DiffAdded = n.GetLongValue(); } },
                { "diff_copied", n => { DiffCopied = n.GetLongValue(); } },
                { "diff_equal", n => { DiffEqual = n.GetLongValue(); } },
                { "diff_moved", n => { DiffMoved = n.GetLongValue(); } },
                { "diff_relocated", n => { DiffRelocated = n.GetLongValue(); } },
                { "diff_removed", n => { DiffRemoved = n.GetLongValue(); } },
                { "diff_restored", n => { DiffRestored = n.GetLongValue(); } },
                { "diff_updated", n => { DiffUpdated = n.GetLongValue(); } },
                { "diffs", n => { Diffs = n.GetCollectionOfObjectValues<global::SnapraidDeamonApi.Models.Diff>(global::SnapraidDeamonApi.Models.Diff.CreateFromDiscriminatorValue)?.AsList(); } },
                { "engine_conf", n => { EngineConf = n.GetStringValue(); } },
                { "engine_content", n => { EngineContent = n.GetStringValue(); } },
                { "engine_version", n => { EngineVersion = n.GetStringValue(); } },
                { "extra_disks_count", n => { ExtraDisksCount = n.GetIntValue(); } },
                { "failure_probability", n => { FailureProbability = n.GetDoubleValue(); } },
                { "files_count", n => { FilesCount = n.GetLongValue(); } },
                { "fix_recovered", n => { FixRecovered = n.GetLongValue(); } },
                { "fix_unrecoverable", n => { FixUnrecoverable = n.GetLongValue(); } },
                { "fixes", n => { Fixes = n.GetCollectionOfObjectValues<global::SnapraidDeamonApi.Models.Fix>(global::SnapraidDeamonApi.Models.Fix.CreateFromDiscriminatorValue)?.AsList(); } },
                { "free_space_bytes", n => { FreeSpaceBytes = n.GetLongValue(); } },
                { "health", n => { Health = n.GetEnumValue<global::SnapraidDeamonApi.Models.Array_health>(); } },
                { "hold_off", n => { HoldOff = n.GetBoolValue(); } },
                { "last_command", n => { LastCommand = n.GetEnumValue<global::SnapraidDeamonApi.Models.Array_last_command>(); } },
                { "last_command_at", n => { LastCommandAt = n.GetStringValue(); } },
                { "last_diff_at", n => { LastDiffAt = n.GetStringValue(); } },
                { "last_fix_at", n => { LastFixAt = n.GetStringValue(); } },
                { "last_scrub_at", n => { LastScrubAt = n.GetStringValue(); } },
                { "last_sync_at", n => { LastSyncAt = n.GetStringValue(); } },
                { "parity_disks_count", n => { ParityDisksCount = n.GetIntValue(); } },
                { "scrub_history", n => { ScrubHistory = n.GetObjectValue<global::SnapraidDeamonApi.Models.ScrubHistory>(global::SnapraidDeamonApi.Models.ScrubHistory.CreateFromDiscriminatorValue); } },
                { "total_space_bytes", n => { TotalSpaceBytes = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("annual_failure_rate", AnnualFailureRate);
            writer.WriteLongValue("blocks_bad", BlocksBad);
            writer.WriteLongValue("blocks_count", BlocksCount);
            writer.WriteIntValue("block_size_bytes", BlockSizeBytes);
            writer.WriteLongValue("blocks_rehash", BlocksRehash);
            writer.WriteLongValue("blocks_unscrubbed", BlocksUnscrubbed);
            writer.WriteLongValue("blocks_unsynced", BlocksUnsynced);
            writer.WriteStringValue("daemon_conf", DaemonConf);
            writer.WriteStringValue("daemon_version", DaemonVersion);
            writer.WriteIntValue("data_disks_count", DataDisksCount);
            writer.WriteLongValue("diff_added", DiffAdded);
            writer.WriteLongValue("diff_copied", DiffCopied);
            writer.WriteLongValue("diff_equal", DiffEqual);
            writer.WriteLongValue("diff_moved", DiffMoved);
            writer.WriteLongValue("diff_relocated", DiffRelocated);
            writer.WriteLongValue("diff_removed", DiffRemoved);
            writer.WriteLongValue("diff_restored", DiffRestored);
            writer.WriteCollectionOfObjectValues<global::SnapraidDeamonApi.Models.Diff>("diffs", Diffs);
            writer.WriteLongValue("diff_updated", DiffUpdated);
            writer.WriteStringValue("engine_conf", EngineConf);
            writer.WriteStringValue("engine_content", EngineContent);
            writer.WriteStringValue("engine_version", EngineVersion);
            writer.WriteIntValue("extra_disks_count", ExtraDisksCount);
            writer.WriteDoubleValue("failure_probability", FailureProbability);
            writer.WriteLongValue("files_count", FilesCount);
            writer.WriteCollectionOfObjectValues<global::SnapraidDeamonApi.Models.Fix>("fixes", Fixes);
            writer.WriteLongValue("fix_recovered", FixRecovered);
            writer.WriteLongValue("fix_unrecoverable", FixUnrecoverable);
            writer.WriteLongValue("free_space_bytes", FreeSpaceBytes);
            writer.WriteEnumValue<global::SnapraidDeamonApi.Models.Array_health>("health", Health);
            writer.WriteBoolValue("hold_off", HoldOff);
            writer.WriteEnumValue<global::SnapraidDeamonApi.Models.Array_last_command>("last_command", LastCommand);
            writer.WriteStringValue("last_command_at", LastCommandAt);
            writer.WriteStringValue("last_diff_at", LastDiffAt);
            writer.WriteStringValue("last_fix_at", LastFixAt);
            writer.WriteStringValue("last_scrub_at", LastScrubAt);
            writer.WriteStringValue("last_sync_at", LastSyncAt);
            writer.WriteIntValue("parity_disks_count", ParityDisksCount);
            writer.WriteObjectValue<global::SnapraidDeamonApi.Models.ScrubHistory>("scrub_history", ScrubHistory);
            writer.WriteLongValue("total_space_bytes", TotalSpaceBytes);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
