// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SnapraidDeamonApi.Models
{
    /// <summary>Identifier of the last successfully completed command.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Array_last_command
    {
        [EnumMember(Value = "probe")]
        #pragma warning disable CS1591
        Probe,
        #pragma warning restore CS1591
        [EnumMember(Value = "up")]
        #pragma warning disable CS1591
        Up,
        #pragma warning restore CS1591
        [EnumMember(Value = "down")]
        #pragma warning disable CS1591
        Down,
        #pragma warning restore CS1591
        [EnumMember(Value = "smart")]
        #pragma warning disable CS1591
        Smart,
        #pragma warning restore CS1591
        [EnumMember(Value = "diff")]
        #pragma warning disable CS1591
        Diff,
        #pragma warning restore CS1591
        [EnumMember(Value = "sync")]
        #pragma warning disable CS1591
        Sync,
        #pragma warning restore CS1591
        [EnumMember(Value = "scrub")]
        #pragma warning disable CS1591
        Scrub,
        #pragma warning restore CS1591
        [EnumMember(Value = "check")]
        #pragma warning disable CS1591
        Check,
        #pragma warning restore CS1591
        [EnumMember(Value = "fix")]
        #pragma warning disable CS1591
        Fix,
        #pragma warning restore CS1591
        [EnumMember(Value = "report")]
        #pragma warning disable CS1591
        Report,
        #pragma warning restore CS1591
        [EnumMember(Value = "down_idle")]
        #pragma warning disable CS1591
        Down_idle,
        #pragma warning restore CS1591
    }
}
