// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SnapraidDeamonApi.Models
{
    /// <summary>
    /// Optional configuration for the task.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CommandRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Optional filters (e.g., &apos;dir/&apos;, &apos;*.txt&apos;) to limit the restoration scope. Each item corresponds to a &apos;-f&apos; argument in the SnapRAID CLI. Valid only for `undelete`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Filters { get; set; }
#nullable restore
#else
        public List<string> Filters { get; set; }
#endif
        /// <summary>If true, the maintenance task will ignore any configured thresholds and proceed with the sync commands. Valid only for `maintenance`.</summary>
        public bool? IgnoreThresholds { get; set; }
        /// <summary>If true, the daemon will command all disks in the array to enter STANDBY mode once the task finishes succesfully or fails.</summary>
        public bool? SpindownOnFinish { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Models.CommandRequest"/> and sets the default values.
        /// </summary>
        public CommandRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Models.CommandRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SnapraidDeamonApi.Models.CommandRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SnapraidDeamonApi.Models.CommandRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "filters", n => { Filters = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "ignore_thresholds", n => { IgnoreThresholds = n.GetBoolValue(); } },
                { "spindown_on_finish", n => { SpindownOnFinish = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("filters", Filters);
            writer.WriteBoolValue("ignore_thresholds", IgnoreThresholds);
            writer.WriteBoolValue("spindown_on_finish", SpindownOnFinish);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
