// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SnapraidDeamonApi.Models
{
    /// <summary>Minimum severity filter for task-related syslog entries. Defaults to &apos;error&apos; if unset.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Config_notify_syslog_level
    {
        [EnumMember(Value = "critical")]
        #pragma warning disable CS1591
        Critical,
        #pragma warning restore CS1591
        [EnumMember(Value = "error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
        [EnumMember(Value = "warning")]
        #pragma warning disable CS1591
        Warning,
        #pragma warning restore CS1591
        [EnumMember(Value = "info")]
        #pragma warning disable CS1591
        Info,
        #pragma warning restore CS1591
    }
}
