// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SnapraidDeamonApi.Models
{
    /// <summary>
    /// Global configuration state for the SnapRAID Daemon.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Config : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Indicates whether security-sensitive configuration parameters can be modified dynamically.If set to false, the following restricted options are forced into a read-only state for all API requests: - hook_run_as_user - hook_script - notify_run_as_user - notify_heartbeat - notify_resultNote that this flag itself is immutable via the API and can only be changed by manually editing the &apos;snapraidd.conf&apos; file and reloading the daemon.</summary>
        public bool? ConfigFullAccess { get; set; }
        /// <summary>The system user account utilized for the execution of &apos;hook_script&apos;.If this parameter is null or empty, the scripts inherit the process privileges of the running daemon.For security enforcement, this parameter is immutable via the REST API unless &apos;net_config_full_access&apos; is explicitly enabled in the static configuration file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HookRunAsUser { get; set; }
#nullable restore
#else
        public string HookRunAsUser { get; set; }
#endif
        /// <summary>Absolute path to a custom script to trigger custom logic for various daemon events.For security enforcement, this parameter is immutable via the REST API unless &apos;net_config_full_access&apos; is explicitly enabled in the static configuration file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HookScript { get; set; }
#nullable restore
#else
        public string HookScript { get; set; }
#endif
        /// <summary>Execution schedule for the automated &apos;sync&apos; and &apos;scrub&apos; sequence. Accepted formats: &quot;HH:MM&quot; or &quot;&lt;day&gt; HH:MM&quot;. If empty, background maintenance is disabled.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MaintenanceSchedule { get; set; }
#nullable restore
#else
        public string MaintenanceSchedule { get; set; }
#endif
        /// <summary>Includes a detailed list of added/removed/modified files in the &apos;notify_result&apos; report bodies.</summary>
        public bool? NotifyDifferences { get; set; }
        /// <summary>Shell command executed only upon task success (exit code 0). Used for external &apos;dead man&apos;s switch&apos; telemetry. Disabled if empty.For security enforcement, this parameter is immutable via the REST API unless &apos;net_config_full_access&apos; is explicitly enabled in the static configuration file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NotifyHeartbeat { get; set; }
#nullable restore
#else
        public string NotifyHeartbeat { get; set; }
#endif
        /// <summary>Shell command executed after task completion. The daemon pipes the task report (plain-text) into the command&apos;s stdin. Use the %s placeholder for dynamic injection of the subject string.For security enforcement, this parameter is immutable via the REST API unless &apos;net_config_full_access&apos; is explicitly enabled in the static configuration file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NotifyResult { get; set; }
#nullable restore
#else
        public string NotifyResult { get; set; }
#endif
        /// <summary>Minimum severity threshold required to trigger the &apos;notify_result&apos; command. Defaults to &apos;error&apos; if unset.</summary>
        public global::SnapraidDeamonApi.Models.Config_notify_result_level? NotifyResultLevel { get; set; }
        /// <summary>Specifies the system user account under which notification subprocesses are executed.This setting governs the execution privileges for heartbeat pings, result shell commands (notify_result).If left blank or omitted, these subprocesses inherit the current privileges of the snapraidd daemon.For security enforcement, this parameter is immutable via the REST API unless &apos;net_config_full_access&apos; is explicitly enabled in the static configuration file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NotifyRunAsUser { get; set; }
#nullable restore
#else
        public string NotifyRunAsUser { get; set; }
#endif
        /// <summary>Enables logging to syslog/journald. Lifecycle events (start, stop, reload) are logged regardless of severity level if this is true.</summary>
        public bool? NotifySyslogEnabled { get; set; }
        /// <summary>Minimum severity filter for task-related syslog entries. Defaults to &apos;error&apos; if unset.</summary>
        public global::SnapraidDeamonApi.Models.Config_notify_syslog_level? NotifySyslogLevel { get; set; }
        /// <summary>Interval for background health monitoring. The daemon probes disk power state. SMART attributes are only queried if the disk is already in an active/idle state to prevent spin-up. Set to 0 to disable monitoring.</summary>
        public int? ProbeIntervalMinutes { get; set; }
        /// <summary>Restricts scrubbing to data blocks not verified within the last N days. Set to 0 to ignore block age.This setting is enforced during scheduled maintenance and calls to &apos;maintenance&apos;. It is BYPASSED for direct calls to &apos;scrub&apos;.</summary>
        public int? ScrubOlderThan { get; set; }
        /// <summary>The percentage of the array verified during the scrub phase of scheduled maintenance. Set to 0 to skip the scrub phase.This setting is enforced during scheduled maintenance and calls to &apos;maintenance&apos;. It is BYPASSED for direct calls to &apos;scrub&apos;.</summary>
        public float? ScrubPercentage { get; set; }
        /// <summary>Inactivity threshold for disk spindown. Activity defined as physical read/write I/O. Power-state probes do not reset this timer but allow more frequent I/O detection. Set to 0 to disable.</summary>
        public int? SpindownIdleMinutes { get; set; }
        /// <summary>Calculates hashes for new or modified files before updating parity. Protects against integrating data corrupted by faulty RAM or cables.</summary>
        public bool? SyncPrehash { get; set; }
        /// <summary>Stops the synchronization if files that previously contained data are now empty. This acts as a safety barrier to prevent parity updates when data may have been accidentally cleared.</summary>
        public bool? SyncPreventTruncations { get; set; }
        /// <summary>Threshold for deleted files. If the number of missing files exceeds this value, the sync operation is suspended.This threshold is strictly enforced during scheduled maintenance and calls to &apos;maintenance&apos;. It is BYPASSED for direct calls to &apos;sync&apos;, allowing the user to force a sync via the API. Set to 0 for no threshold.</summary>
        public int? SyncThresholdDeletes { get; set; }
        /// <summary>Threshold for updated files. If the number of files with changed sizes or timestamps exceeds this value, the sync operation is suspended.This threshold is strictly enforced during scheduled maintenance and calls to &apos;maintenance&apos;. It is BYPASSED for direct calls to &apos;sync&apos;, allowing the user to force a sync via the API. Set to 0 for no threshold.</summary>
        public int? SyncThresholdUpdates { get; set; }
        /// <summary>Enables a specific timestamp alignment pass as part of the automated maintenance sequence. The scope of this setting is to correct file metadata on filesystems that lack sub-second precision (zeroed nanoseconds). By refreshing these attributes to a random sub-second value, the engine can reliably distinguish between files that were moved or renamed versus those that are new. This is executed via the &apos;touch&apos; command immediately before the sync phase of the maintenance window to ensure high- resolution tracking and prevent unnecessary parity re-computation.</summary>
        public int? TouchZeroSubseconds { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Models.Config"/> and sets the default values.
        /// </summary>
        public Config()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Models.Config"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SnapraidDeamonApi.Models.Config CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SnapraidDeamonApi.Models.Config();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "config_full_access", n => { ConfigFullAccess = n.GetBoolValue(); } },
                { "hook_run_as_user", n => { HookRunAsUser = n.GetStringValue(); } },
                { "hook_script", n => { HookScript = n.GetStringValue(); } },
                { "maintenance_schedule", n => { MaintenanceSchedule = n.GetStringValue(); } },
                { "notify_differences", n => { NotifyDifferences = n.GetBoolValue(); } },
                { "notify_heartbeat", n => { NotifyHeartbeat = n.GetStringValue(); } },
                { "notify_result", n => { NotifyResult = n.GetStringValue(); } },
                { "notify_result_level", n => { NotifyResultLevel = n.GetEnumValue<global::SnapraidDeamonApi.Models.Config_notify_result_level>(); } },
                { "notify_run_as_user", n => { NotifyRunAsUser = n.GetStringValue(); } },
                { "notify_syslog_enabled", n => { NotifySyslogEnabled = n.GetBoolValue(); } },
                { "notify_syslog_level", n => { NotifySyslogLevel = n.GetEnumValue<global::SnapraidDeamonApi.Models.Config_notify_syslog_level>(); } },
                { "probe_interval_minutes", n => { ProbeIntervalMinutes = n.GetIntValue(); } },
                { "scrub_older_than", n => { ScrubOlderThan = n.GetIntValue(); } },
                { "scrub_percentage", n => { ScrubPercentage = n.GetFloatValue(); } },
                { "spindown_idle_minutes", n => { SpindownIdleMinutes = n.GetIntValue(); } },
                { "sync_prehash", n => { SyncPrehash = n.GetBoolValue(); } },
                { "sync_prevent_truncations", n => { SyncPreventTruncations = n.GetBoolValue(); } },
                { "sync_threshold_deletes", n => { SyncThresholdDeletes = n.GetIntValue(); } },
                { "sync_threshold_updates", n => { SyncThresholdUpdates = n.GetIntValue(); } },
                { "touch_zero_subseconds", n => { TouchZeroSubseconds = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("config_full_access", ConfigFullAccess);
            writer.WriteStringValue("hook_run_as_user", HookRunAsUser);
            writer.WriteStringValue("hook_script", HookScript);
            writer.WriteStringValue("maintenance_schedule", MaintenanceSchedule);
            writer.WriteBoolValue("notify_differences", NotifyDifferences);
            writer.WriteStringValue("notify_heartbeat", NotifyHeartbeat);
            writer.WriteStringValue("notify_result", NotifyResult);
            writer.WriteEnumValue<global::SnapraidDeamonApi.Models.Config_notify_result_level>("notify_result_level", NotifyResultLevel);
            writer.WriteStringValue("notify_run_as_user", NotifyRunAsUser);
            writer.WriteBoolValue("notify_syslog_enabled", NotifySyslogEnabled);
            writer.WriteEnumValue<global::SnapraidDeamonApi.Models.Config_notify_syslog_level>("notify_syslog_level", NotifySyslogLevel);
            writer.WriteIntValue("probe_interval_minutes", ProbeIntervalMinutes);
            writer.WriteIntValue("scrub_older_than", ScrubOlderThan);
            writer.WriteFloatValue("scrub_percentage", ScrubPercentage);
            writer.WriteIntValue("spindown_idle_minutes", SpindownIdleMinutes);
            writer.WriteBoolValue("sync_prehash", SyncPrehash);
            writer.WriteBoolValue("sync_prevent_truncations", SyncPreventTruncations);
            writer.WriteIntValue("sync_threshold_deletes", SyncThresholdDeletes);
            writer.WriteIntValue("sync_threshold_updates", SyncThresholdUpdates);
            writer.WriteIntValue("touch_zero_subseconds", TouchZeroSubseconds);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
