// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SnapraidDeamonApi.Models
{
    /// <summary>Indicates if this attribute is a &apos;pre-fail&apos; indicator or a &apos;oldage&apos; informational value.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Device_smart_attributes_type
    {
        [EnumMember(Value = "prefail")]
        #pragma warning disable CS1591
        Prefail,
        #pragma warning restore CS1591
        [EnumMember(Value = "oldage")]
        #pragma warning disable CS1591
        Oldage,
        #pragma warning restore CS1591
    }
}
