// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SnapraidDeamonApi.Models
{
    /// <summary>The current mechanical power state of the physical device.* &apos;active&apos;: The disk is spun up and the platters are rotating at  full speed. The device is ready for immediate I/O.* &apos;standby&apos;: The disk is spun down (low-power mode). The platters  are stationary. Any subsequent I/O will incur a spin-up delay.* &apos;pending&apos;: The power state has not yet been determined. This is  the default state upon daemon startup until the first hardware  probe is performed.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Device_power
    {
        [EnumMember(Value = "active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "standby")]
        #pragma warning disable CS1591
        Standby,
        #pragma warning restore CS1591
        [EnumMember(Value = "pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
    }
}
