// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SnapraidDeamonApi.Models
{
    /// <summary>The failure history of this specific attribute. &apos;never&apos; indicates it has always been within limits; &apos;now&apos; indicates the attribute currently exceeds the threshold; &apos;past&apos; indicates the attribute was out of limits at some point in the drive&apos;s history but has since returned to a nominal normalized value.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Device_smart_attributes_when_failed
    {
        [EnumMember(Value = "never")]
        #pragma warning disable CS1591
        Never,
        #pragma warning restore CS1591
        [EnumMember(Value = "now")]
        #pragma warning disable CS1591
        Now,
        #pragma warning restore CS1591
        [EnumMember(Value = "past")]
        #pragma warning disable CS1591
        Past,
        #pragma warning restore CS1591
    }
}
