// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SnapraidDeamonApi.Models
{
    /// <summary>The category of measurement for the &apos;raw&apos; value: &apos;size&apos;: Size-based metric in bytes (e.g., Total_LBAs_Written). &apos;time&apos;: Duration measured in seconds (e.g., Power_On_Hours). &apos;temperature&apos;: Thermal value in degrees Celsius. &apos;count&apos;: A discrete event counter where an increase signifies worsening conditions (e.g., Reallocated_Sector_Ct). &apos;use_ratio&apos;: A percentage increasing from 0 to 100, typically used for resource utilization or wear accumulation. &apos;life_ratio&apos;: A percentage decreasing from 100 to 0, representing remaining health or estimated life. &apos;vendor&apos;: An opaque raw value that does not map to a standard unit and should be treated as informational.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Device_smart_attributes_measure
    {
        [EnumMember(Value = "size")]
        #pragma warning disable CS1591
        Size,
        #pragma warning restore CS1591
        [EnumMember(Value = "time")]
        #pragma warning disable CS1591
        Time,
        #pragma warning restore CS1591
        [EnumMember(Value = "temperature")]
        #pragma warning disable CS1591
        Temperature,
        #pragma warning restore CS1591
        [EnumMember(Value = "count")]
        #pragma warning disable CS1591
        Count,
        #pragma warning restore CS1591
        [EnumMember(Value = "use_ratio")]
        #pragma warning disable CS1591
        Use_ratio,
        #pragma warning restore CS1591
        [EnumMember(Value = "life_ratio")]
        #pragma warning disable CS1591
        Life_ratio,
        #pragma warning restore CS1591
        [EnumMember(Value = "vendor")]
        #pragma warning disable CS1591
        Vendor,
        #pragma warning restore CS1591
    }
}
