// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SnapraidDeamonApi.Models
{
    /// <summary>
    /// The S.M.A.R.T. telemetry and interpreted health analysis for the physical disk.This object combines raw attribute counters with boolean flags derived from smartctl exit codes (bitmask 1 &lt;&lt; 3 to 1 &lt;&lt; 7). It is omitted if the disk is in standby.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Device_smart : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A collection of all S.M.A.R.T. telemetry attributes retrieved from the disk firmware, providing detailed health metrics.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SnapraidDeamonApi.Models.Device_smart_attributes>? Attributes { get; set; }
#nullable restore
#else
        public List<global::SnapraidDeamonApi.Models.Device_smart_attributes> Attributes { get; set; }
#endif
        /// <summary>The internal device error log contains records of summary errors.</summary>
        public bool? ErrorLogged { get; set; }
        /// <summary>The drive firmware explicitly reports that the disk is currently failing the health status check.</summary>
        public bool? Failing { get; set; }
        /// <summary>The timestamp representing the exact moment the S.M.A.R.T. telemetry was captured from the physical disk. This serves as the &quot;heartbeat&quot; for health data, allowing the system to determine the age and relevance of the current diagnostic metrics.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MeasuredAt { get; set; }
#nullable restore
#else
        public string MeasuredAt { get; set; }
#endif
        /// <summary>The total number of hours the drive has been powered on. This field acts as a unified entry point, abstracting the data from various possible S.M.A.R.T. attributes (such as IDs 9) Used as a primary metric for determining the age and remaining service life of the physical disk.</summary>
        public int? PowerOnHours { get; set; }
        /// <summary>One or more critical &apos;Prefail&apos; attributes are currently at or below the manufacturer&apos;s threshold.</summary>
        public bool? Prefail { get; set; }
        /// <summary>The status is &apos;OK&apos;, but attributes have dropped below the threshold at some point in the device&apos;s history.</summary>
        public bool? PrefailLogged { get; set; }
        /// <summary>The self-test log contains records of failed or aborted tests.</summary>
        public bool? SelftestErrorLogged { get; set; }
        /// <summary>The current internal temperature of the drive in degrees Celsius. This field acts as a unified entry point, abstracting the data from various possible S.M.A.R.T. attributes (such as IDs 190 or 194) depending on the manufacturer&apos;s implementation. Centralizing this value ensures consistent monitoring regardless of the drive model. Maintaining consistent temperatures below 45°C is critical for the long-term reliability of the drive platters and motor.</summary>
        public int? TemperatureCelsius { get; set; }
        /// <summary>The highest recorded internal temperature of the drive in degrees Celsius. Exceeding manufacturer limits (often 55-60°C) typically triggers a PREFAIL status.</summary>
        public int? TemperatureMaxCelsius { get; set; }
        /// <summary>The lowest recorded internal temperature of the drive in degrees Celsius during the current power-on session or drive lifetime.</summary>
        public int? TemperatureMinCelsius { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Models.Device_smart"/> and sets the default values.
        /// </summary>
        public Device_smart()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Models.Device_smart"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SnapraidDeamonApi.Models.Device_smart CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SnapraidDeamonApi.Models.Device_smart();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attributes", n => { Attributes = n.GetCollectionOfObjectValues<global::SnapraidDeamonApi.Models.Device_smart_attributes>(global::SnapraidDeamonApi.Models.Device_smart_attributes.CreateFromDiscriminatorValue)?.AsList(); } },
                { "error_logged", n => { ErrorLogged = n.GetBoolValue(); } },
                { "failing", n => { Failing = n.GetBoolValue(); } },
                { "measured_at", n => { MeasuredAt = n.GetStringValue(); } },
                { "power_on_hours", n => { PowerOnHours = n.GetIntValue(); } },
                { "prefail", n => { Prefail = n.GetBoolValue(); } },
                { "prefail_logged", n => { PrefailLogged = n.GetBoolValue(); } },
                { "selftest_error_logged", n => { SelftestErrorLogged = n.GetBoolValue(); } },
                { "temperature_celsius", n => { TemperatureCelsius = n.GetIntValue(); } },
                { "temperature_max_celsius", n => { TemperatureMaxCelsius = n.GetIntValue(); } },
                { "temperature_min_celsius", n => { TemperatureMinCelsius = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::SnapraidDeamonApi.Models.Device_smart_attributes>("attributes", Attributes);
            writer.WriteBoolValue("error_logged", ErrorLogged);
            writer.WriteBoolValue("failing", Failing);
            writer.WriteStringValue("measured_at", MeasuredAt);
            writer.WriteIntValue("power_on_hours", PowerOnHours);
            writer.WriteBoolValue("prefail", Prefail);
            writer.WriteBoolValue("prefail_logged", PrefailLogged);
            writer.WriteBoolValue("selftest_error_logged", SelftestErrorLogged);
            writer.WriteIntValue("temperature_celsius", TemperatureCelsius);
            writer.WriteIntValue("temperature_max_celsius", TemperatureMaxCelsius);
            writer.WriteIntValue("temperature_min_celsius", TemperatureMinCelsius);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
