// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SnapraidDeamonApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Device : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The Annual Failure Rate (the average numberof failures you expect in a year) computed from the SMART attributes 5, 187, 188, 197, 198.</summary>
        public double? AnnualFailureRate { get; set; }
        /// <summary>Counts media-level errors where data could not be reliably read or written. These indicate actual storage surface or flash failures and may imply data loss. This counter is cumulative and never resets to zero, even if the underlying error condition is resolved.</summary>
        public long? ErrorMedium { get; set; }
        /// <summary>Historical metadata and change tracking for a parent value. The entire object is omitted if the value has never changed since the daemon started.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SnapraidDeamonApi.Models.ValueHistory? ErrorMediumHistory { get; set; }
#nullable restore
#else
        public global::SnapraidDeamonApi.Models.ValueHistory ErrorMediumHistory { get; set; }
#endif
        /// <summary>Counts command, transport, or controller-level errors reported by the device. These reflect failed I/O operations not directly caused by media defects (for example interface, firmware, or power-related errors). This counter is cumulative and never resets to zero, even if the underlying error condition is resolved.</summary>
        public long? ErrorProtocol { get; set; }
        /// <summary>Historical metadata and change tracking for a parent value. The entire object is omitted if the value has never changed since the daemon started.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SnapraidDeamonApi.Models.ValueHistory? ErrorProtocolHistory { get; set; }
#nullable restore
#else
        public global::SnapraidDeamonApi.Models.ValueHistory ErrorProtocolHistory { get; set; }
#endif
        /// <summary>Statistical probability of at least one disk failure within a one-year period, calculated using a Poisson distribution model based on the aggregate Annual Failure Rate.</summary>
        public double? FailureProbability { get; set; }
        /// <summary>Vendor and Model Family.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Family { get; set; }
#nullable restore
#else
        public string Family { get; set; }
#endif
        /// <summary>The aggregate health status of the physical hardware device.* passed: The device is operating within normal  manufacturer specifications with no logged errors.* prefail: The drive has encountered hardware I/O errors or a  SMART prefail condition.* failing: The drive has encountered a SMART failing condition. * pending: The health has not yet been determined.Note that there is no silent error detection at device level, and the &apos;corrupt&apos; health state is not possible.</summary>
        public global::SnapraidDeamonApi.Models.Device_health? Health { get; set; }
        /// <summary>A list of unique hardware identifiers associated with the device. This may include the Serial Number, WWN, and UUIDs. These are used to persistently identify the disk regardless of changes to the device node path.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Ids { get; set; }
#nullable restore
#else
        public List<string> Ids { get; set; }
#endif
        /// <summary>Interface of the disk. Typical values are SATA, SCSI, USB, NVMe.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Interface { get; set; }
#nullable restore
#else
        public string Interface { get; set; }
#endif
        /// <summary>Model of the disk.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>System device path (e.g., /dev/sdb1).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Node { get; set; }
#nullable restore
#else
        public string Node { get; set; }
#endif
        /// <summary>The current mechanical power state of the physical device.* &apos;active&apos;: The disk is spun up and the platters are rotating at  full speed. The device is ready for immediate I/O.* &apos;standby&apos;: The disk is spun down (low-power mode). The platters  are stationary. Any subsequent I/O will incur a spin-up delay.* &apos;pending&apos;: The power state has not yet been determined. This is  the default state upon daemon startup until the first hardware  probe is performed.</summary>
        public global::SnapraidDeamonApi.Models.Device_power? Power { get; set; }
        /// <summary>The nominal rotation rate of the device in Revolutions Per Minute (RPM). Use this to distinguish between mechanical and solid-state storage: * 0: Non-rotational device (e.g., SSD, NVMe). * 1: Rotational device with an unknown or undetected speed. * &gt;1: The actual detected rotational speed (e.g., 5400, 7200, 10000).</summary>
        public int? Rotational { get; set; }
        /// <summary>Serial of the disk.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Serial { get; set; }
#nullable restore
#else
        public string Serial { get; set; }
#endif
        /// <summary>Size in bytes of the raw device.</summary>
        public long? SizeBytes { get; set; }
        /// <summary>The S.M.A.R.T. telemetry and interpreted health analysis for the physical disk.This object combines raw attribute counters with boolean flags derived from smartctl exit codes (bitmask 1 &lt;&lt; 3 to 1 &lt;&lt; 7). It is omitted if the disk is in standby.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SnapraidDeamonApi.Models.Device_smart? Smart { get; set; }
#nullable restore
#else
        public global::SnapraidDeamonApi.Models.Device_smart Smart { get; set; }
#endif
        /// <summary>The zero-based index of the logical partition within the &apos;splits&apos; array. This index links the physical device to its specific configuration entry, identifying which mount point or parity file path or data disk mount point resides on this particular hardware block device.</summary>
        public int? SplitIndex { get; set; }
        /// <summary>A rolling 24-hour history of temperatures measured every 10 minutes (144 points total). - Value 0: Standby mode - Index 0 is 24h ago; Index 143 is current.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? TempHistory24h { get; set; }
#nullable restore
#else
        public List<int?> TempHistory24h { get; set; }
#endif
        /// <summary>The wear level of the SSD/NVME expressed as a percentage, where a value of 0 represents a brand new drive with zero wear and a value of 100 indicates the drive has reached or exceeded its manufacturer-rated design life. This metric is provided as a normalized unsigned integer, offering a consistent health indicator across various SSD/NVME vendors and interface types by mapping diverse hardware counters into a single standardized scale.</summary>
        public int? WearLevel { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Models.Device"/> and sets the default values.
        /// </summary>
        public Device()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Models.Device"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SnapraidDeamonApi.Models.Device CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SnapraidDeamonApi.Models.Device();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "annual_failure_rate", n => { AnnualFailureRate = n.GetDoubleValue(); } },
                { "error_medium", n => { ErrorMedium = n.GetLongValue(); } },
                { "error_medium_history", n => { ErrorMediumHistory = n.GetObjectValue<global::SnapraidDeamonApi.Models.ValueHistory>(global::SnapraidDeamonApi.Models.ValueHistory.CreateFromDiscriminatorValue); } },
                { "error_protocol", n => { ErrorProtocol = n.GetLongValue(); } },
                { "error_protocol_history", n => { ErrorProtocolHistory = n.GetObjectValue<global::SnapraidDeamonApi.Models.ValueHistory>(global::SnapraidDeamonApi.Models.ValueHistory.CreateFromDiscriminatorValue); } },
                { "failure_probability", n => { FailureProbability = n.GetDoubleValue(); } },
                { "family", n => { Family = n.GetStringValue(); } },
                { "health", n => { Health = n.GetEnumValue<global::SnapraidDeamonApi.Models.Device_health>(); } },
                { "ids", n => { Ids = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "interface", n => { Interface = n.GetStringValue(); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "node", n => { Node = n.GetStringValue(); } },
                { "power", n => { Power = n.GetEnumValue<global::SnapraidDeamonApi.Models.Device_power>(); } },
                { "rotational", n => { Rotational = n.GetIntValue(); } },
                { "serial", n => { Serial = n.GetStringValue(); } },
                { "size_bytes", n => { SizeBytes = n.GetLongValue(); } },
                { "smart", n => { Smart = n.GetObjectValue<global::SnapraidDeamonApi.Models.Device_smart>(global::SnapraidDeamonApi.Models.Device_smart.CreateFromDiscriminatorValue); } },
                { "split_index", n => { SplitIndex = n.GetIntValue(); } },
                { "temp_history_24h", n => { TempHistory24h = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "wear_level", n => { WearLevel = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("annual_failure_rate", AnnualFailureRate);
            writer.WriteLongValue("error_medium", ErrorMedium);
            writer.WriteObjectValue<global::SnapraidDeamonApi.Models.ValueHistory>("error_medium_history", ErrorMediumHistory);
            writer.WriteLongValue("error_protocol", ErrorProtocol);
            writer.WriteObjectValue<global::SnapraidDeamonApi.Models.ValueHistory>("error_protocol_history", ErrorProtocolHistory);
            writer.WriteDoubleValue("failure_probability", FailureProbability);
            writer.WriteStringValue("family", Family);
            writer.WriteEnumValue<global::SnapraidDeamonApi.Models.Device_health>("health", Health);
            writer.WriteCollectionOfPrimitiveValues<string>("ids", Ids);
            writer.WriteStringValue("interface", Interface);
            writer.WriteStringValue("model", Model);
            writer.WriteStringValue("node", Node);
            writer.WriteEnumValue<global::SnapraidDeamonApi.Models.Device_power>("power", Power);
            writer.WriteIntValue("rotational", Rotational);
            writer.WriteStringValue("serial", Serial);
            writer.WriteLongValue("size_bytes", SizeBytes);
            writer.WriteObjectValue<global::SnapraidDeamonApi.Models.Device_smart>("smart", Smart);
            writer.WriteIntValue("split_index", SplitIndex);
            writer.WriteCollectionOfPrimitiveValues<int?>("temp_history_24h", TempHistory24h);
            writer.WriteIntValue("wear_level", WearLevel);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
