// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SnapraidDeamonApi.Models
{
    /// <summary>The aggregate health status of the physical hardware device.* passed: The device is operating within normal  manufacturer specifications with no logged errors.* prefail: The drive has encountered hardware I/O errors or a  SMART prefail condition.* failing: The drive has encountered a SMART failing condition. * pending: The health has not yet been determined.Note that there is no silent error detection at device level, and the &apos;corrupt&apos; health state is not possible.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Device_health
    {
        [EnumMember(Value = "passed")]
        #pragma warning disable CS1591
        Passed,
        #pragma warning restore CS1591
        [EnumMember(Value = "prefail")]
        #pragma warning disable CS1591
        Prefail,
        #pragma warning restore CS1591
        [EnumMember(Value = "failing")]
        #pragma warning disable CS1591
        Failing,
        #pragma warning restore CS1591
        [EnumMember(Value = "pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
    }
}
