// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SnapraidDeamonApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Device_smart_attributes : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The lifetime average recorded by the drive firmware itself. This is a hardware-persisted record of the &apos;raw&apos; value that spans the entire life of the disk, independent of the daemon&apos;s tracking.</summary>
        public int? Avg { get; set; }
        /// <summary>Indicates if this attribute is a critical indicator of hardware health. When true, any degradation in this value should be treated as a high-priority warning, regardless of whether the &apos;type&apos; is &apos;prefail&apos; or &apos;oldage&apos;.</summary>
        public bool? Critical { get; set; }
        /// <summary>The absolute lifetime maximum recorded by the drive firmware itself. This is a hardware-persisted record of the &apos;raw&apos; value that spans the entire life of the disk, independent of the daemon&apos;s tracking.</summary>
        public int? Max { get; set; }
        /// <summary>The category of measurement for the &apos;raw&apos; value: &apos;size&apos;: Size-based metric in bytes (e.g., Total_LBAs_Written). &apos;time&apos;: Duration measured in seconds (e.g., Power_On_Hours). &apos;temperature&apos;: Thermal value in degrees Celsius. &apos;count&apos;: A discrete event counter where an increase signifies worsening conditions (e.g., Reallocated_Sector_Ct). &apos;use_ratio&apos;: A percentage increasing from 0 to 100, typically used for resource utilization or wear accumulation. &apos;life_ratio&apos;: A percentage decreasing from 100 to 0, representing remaining health or estimated life. &apos;vendor&apos;: An opaque raw value that does not map to a standard unit and should be treated as informational.</summary>
        public global::SnapraidDeamonApi.Models.Device_smart_attributes_measure? Measure { get; set; }
        /// <summary>The absolute lifetime minimum recorded by the drive firmware itself. This is a hardware-persisted record of the &apos;raw&apos; value that spans the entire life of the disk, independent of the daemon&apos;s tracking.</summary>
        public int? Min { get; set; }
        /// <summary>The technical identifier or human-readable name of the S.M.A.R.T. attribute (e.g., Power_On_Hours).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The current normalized value of the attribute, typically scaled from 100 to 1 (where lower is usually worse).</summary>
        public int? Norm { get; set; }
        /// <summary>The raw value processed by the daemon. This is the actual data point (e.g., total hours or degrees Celsius).</summary>
        public long? Raw { get; set; }
        /// <summary>Historical metadata and change tracking for a parent value. The entire object is omitted if the value has never changed since the daemon started.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SnapraidDeamonApi.Models.ValueHistory? RawHistory { get; set; }
#nullable restore
#else
        public global::SnapraidDeamonApi.Models.ValueHistory RawHistory { get; set; }
#endif
        /// <summary>The manufacturer-defined limit. If &apos;norm&apos; drops below this value, the attribute is considered failed.</summary>
        public int? Thresh { get; set; }
        /// <summary>Indicates if this attribute is a &apos;pre-fail&apos; indicator or a &apos;oldage&apos; informational value.</summary>
        public global::SnapraidDeamonApi.Models.Device_smart_attributes_type? Type { get; set; }
        /// <summary>The multiplier to convert the &apos;raw&apos; value into the base SI unit for the specified &apos;measure&apos;. Note that for &apos;time&apos; the unit may be less than 1 to represent milliseconds. For &apos;bytes&apos;, results in total bytes. For &apos;time&apos;, results in total seconds. For &apos;temperature&apos;, results in Celsius degrees. For &apos;count&apos;, it is a scale factor (usually 1). For &apos;percentage&apos;, it is a scale factor (usually 1).</summary>
        public float? Unit { get; set; }
        /// <summary>The failure history of this specific attribute. &apos;never&apos; indicates it has always been within limits; &apos;now&apos; indicates the attribute currently exceeds the threshold; &apos;past&apos; indicates the attribute was out of limits at some point in the drive&apos;s history but has since returned to a nominal normalized value.</summary>
        public global::SnapraidDeamonApi.Models.Device_smart_attributes_when_failed? WhenFailed { get; set; }
        /// <summary>The lowest normalized value ever recorded for this attribute during the drive&apos;s lifetime.</summary>
        public int? Worst { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Models.Device_smart_attributes"/> and sets the default values.
        /// </summary>
        public Device_smart_attributes()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Models.Device_smart_attributes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SnapraidDeamonApi.Models.Device_smart_attributes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SnapraidDeamonApi.Models.Device_smart_attributes();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "avg", n => { Avg = n.GetIntValue(); } },
                { "critical", n => { Critical = n.GetBoolValue(); } },
                { "max", n => { Max = n.GetIntValue(); } },
                { "measure", n => { Measure = n.GetEnumValue<global::SnapraidDeamonApi.Models.Device_smart_attributes_measure>(); } },
                { "min", n => { Min = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "norm", n => { Norm = n.GetIntValue(); } },
                { "raw", n => { Raw = n.GetLongValue(); } },
                { "raw_history", n => { RawHistory = n.GetObjectValue<global::SnapraidDeamonApi.Models.ValueHistory>(global::SnapraidDeamonApi.Models.ValueHistory.CreateFromDiscriminatorValue); } },
                { "thresh", n => { Thresh = n.GetIntValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::SnapraidDeamonApi.Models.Device_smart_attributes_type>(); } },
                { "unit", n => { Unit = n.GetFloatValue(); } },
                { "when_failed", n => { WhenFailed = n.GetEnumValue<global::SnapraidDeamonApi.Models.Device_smart_attributes_when_failed>(); } },
                { "worst", n => { Worst = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("avg", Avg);
            writer.WriteBoolValue("critical", Critical);
            writer.WriteIntValue("max", Max);
            writer.WriteEnumValue<global::SnapraidDeamonApi.Models.Device_smart_attributes_measure>("measure", Measure);
            writer.WriteIntValue("min", Min);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("norm", Norm);
            writer.WriteLongValue("raw", Raw);
            writer.WriteObjectValue<global::SnapraidDeamonApi.Models.ValueHistory>("raw_history", RawHistory);
            writer.WriteIntValue("thresh", Thresh);
            writer.WriteEnumValue<global::SnapraidDeamonApi.Models.Device_smart_attributes_type>("type", Type);
            writer.WriteFloatValue("unit", Unit);
            writer.WriteEnumValue<global::SnapraidDeamonApi.Models.Device_smart_attributes_when_failed>("when_failed", WhenFailed);
            writer.WriteIntValue("worst", Worst);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
