// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SnapraidDeamonApi.Models
{
    /// <summary>
    /// Represents an individual file change detected during a diff operation.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Diff : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The specific type of change detected: - added: New file not in content file. - removed: File missing from filesystem. - updated: Size, timestamp, or link target changed. - moved: Path changed on the same disk. - copied: New file is a copy from another disk. - relocated: New file is moved from another disk. - restored: Inode changed but metadata matches. Likely a backup restore.</summary>
        public global::SnapraidDeamonApi.Models.Diff_change? Change { get; set; }
        /// <summary>The name of the disk where the file currently resides.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Disk { get; set; }
#nullable restore
#else
        public string Disk { get; set; }
#endif
        /// <summary>The current relative path of the file on the disk.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Path { get; set; }
#nullable restore
#else
        public string Path { get; set; }
#endif
        /// <summary>The name of the originating disk. This field is only populated if the reason is &apos;moved&apos;, &apos;copied&apos; or &apos;relocated&apos;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceDisk { get; set; }
#nullable restore
#else
        public string SourceDisk { get; set; }
#endif
        /// <summary>The original path of the file. This field is only populated if the reason is &apos;moved&apos;, &apos;copied&apos; or &apos;relocated&apos;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourcePath { get; set; }
#nullable restore
#else
        public string SourcePath { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Models.Diff"/> and sets the default values.
        /// </summary>
        public Diff()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Models.Diff"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SnapraidDeamonApi.Models.Diff CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SnapraidDeamonApi.Models.Diff();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "change", n => { Change = n.GetEnumValue<global::SnapraidDeamonApi.Models.Diff_change>(); } },
                { "disk", n => { Disk = n.GetStringValue(); } },
                { "path", n => { Path = n.GetStringValue(); } },
                { "source_disk", n => { SourceDisk = n.GetStringValue(); } },
                { "source_path", n => { SourcePath = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::SnapraidDeamonApi.Models.Diff_change>("change", Change);
            writer.WriteStringValue("disk", Disk);
            writer.WriteStringValue("path", Path);
            writer.WriteStringValue("source_disk", SourceDisk);
            writer.WriteStringValue("source_path", SourcePath);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
