// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SnapraidDeamonApi.Models
{
    /// <summary>The specific type of change detected: - added: New file not in content file. - removed: File missing from filesystem. - updated: Size, timestamp, or link target changed. - moved: Path changed on the same disk. - copied: New file is a copy from another disk. - relocated: New file is moved from another disk. - restored: Inode changed but metadata matches. Likely a backup restore.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Diff_change
    {
        [EnumMember(Value = "added")]
        #pragma warning disable CS1591
        Added,
        #pragma warning restore CS1591
        [EnumMember(Value = "removed")]
        #pragma warning disable CS1591
        Removed,
        #pragma warning restore CS1591
        [EnumMember(Value = "updated")]
        #pragma warning disable CS1591
        Updated,
        #pragma warning restore CS1591
        [EnumMember(Value = "moved")]
        #pragma warning disable CS1591
        Moved,
        #pragma warning restore CS1591
        [EnumMember(Value = "copied")]
        #pragma warning disable CS1591
        Copied,
        #pragma warning restore CS1591
        [EnumMember(Value = "relocated")]
        #pragma warning disable CS1591
        Relocated,
        #pragma warning restore CS1591
        [EnumMember(Value = "restored")]
        #pragma warning disable CS1591
        Restored,
        #pragma warning restore CS1591
    }
}
