// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SnapraidDeamonApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Disk : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The total number of read and write operations processed by the disk since the last system boot. This value is a cumulative counter provided by the kernel.</summary>
        public long? AccessCount { get; set; }
        /// <summary>The number of seconds elapsed since the &apos;access_count&apos; last increased. This value measures continuous inactivity and is used to determine if the disk is a candidate for spin-down to save power.</summary>
        public long? AccessCountIdleDuration { get; set; }
        /// <summary>The timestamp when the daemon first sampled &apos;access_count&apos;. This timestamp is in local time.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccessCountInitialTime { get; set; }
#nullable restore
#else
        public string AccessCountInitialTime { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The devices property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SnapraidDeamonApi.Models.Device>? Devices { get; set; }
#nullable restore
#else
        public List<global::SnapraidDeamonApi.Models.Device> Devices { get; set; }
#endif
        /// <summary>The accumulated count of data integrity errors encountered since the daemon started. This tracks &apos;silent&apos; errors where a read was physically successful, but the data failed checksum verification, across all tasks in the current session. This accumulated counter is cleared after a `scrub` command reports that no blocks are bad.</summary>
        public long? ErrorData { get; set; }
        /// <summary>The accumulated count of physical Input/Output errors encountered since the daemon started. This tracks hardware-level failures (disk, cable, or controller) recorded across all tasks executed during the current session uptime. This accumulated counter is cleared after a `scrub` command reports that no blocks are bad.</summary>
        public long? ErrorIo { get; set; }
        /// <summary>The free space in bytes in the filesystem. In case of parity splitted multiple filesystems, this is the cumulative size.</summary>
        public long? FreeSpaceBytes { get; set; }
        /// <summary>The aggregate operational health of the logical disk.* passed: All member devices are nominal, and no data  inconsistencies are detected.* corrupt: The disk has encountered silent data errors. * prefail: A critical state indicating that one or more  underlying devices have encountered I/O failures, or a  SMART prefail condition.* failing: A critical state indicating that one or more  underlying devices have encountered a SMART failing  condition.* pending: The aggregate health has not yet been  determined.</summary>
        public global::SnapraidDeamonApi.Models.Disk_health? Health { get; set; }
        /// <summary>Logical name (e.g., d1, d2, ..., parity, 2-parity, ...).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The logical power state of the disk, mirrored from the underlying physical device.* &apos;active&apos;: The disk is spun up. Operations like &apos;sync&apos; or &apos;scrub&apos;  on this disk will start immediately.* &apos;standby&apos;: The disk is spun down. Any array operation will  require a 10-15 second spin-up delay before data can be read.* &apos;pending&apos;: The power state is currently unknown. The daemon  is waiting for the next probe or array command to verify if  the disk is spinning.</summary>
        public global::SnapraidDeamonApi.Models.Disk_power? Power { get; set; }
        /// <summary>The splits property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SnapraidDeamonApi.Models.Split>? Splits { get; set; }
#nullable restore
#else
        public List<global::SnapraidDeamonApi.Models.Split> Splits { get; set; }
#endif
        /// <summary>The size in bytes of the filesystem. In case of parity splitted in multiple filesystems, this is the cumulative size.</summary>
        public long? TotalSpaceBytes { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Models.Disk"/> and sets the default values.
        /// </summary>
        public Disk()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Models.Disk"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SnapraidDeamonApi.Models.Disk CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SnapraidDeamonApi.Models.Disk();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "access_count", n => { AccessCount = n.GetLongValue(); } },
                { "access_count_idle_duration", n => { AccessCountIdleDuration = n.GetLongValue(); } },
                { "access_count_initial_time", n => { AccessCountInitialTime = n.GetStringValue(); } },
                { "devices", n => { Devices = n.GetCollectionOfObjectValues<global::SnapraidDeamonApi.Models.Device>(global::SnapraidDeamonApi.Models.Device.CreateFromDiscriminatorValue)?.AsList(); } },
                { "error_data", n => { ErrorData = n.GetLongValue(); } },
                { "error_io", n => { ErrorIo = n.GetLongValue(); } },
                { "free_space_bytes", n => { FreeSpaceBytes = n.GetLongValue(); } },
                { "health", n => { Health = n.GetEnumValue<global::SnapraidDeamonApi.Models.Disk_health>(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "power", n => { Power = n.GetEnumValue<global::SnapraidDeamonApi.Models.Disk_power>(); } },
                { "splits", n => { Splits = n.GetCollectionOfObjectValues<global::SnapraidDeamonApi.Models.Split>(global::SnapraidDeamonApi.Models.Split.CreateFromDiscriminatorValue)?.AsList(); } },
                { "total_space_bytes", n => { TotalSpaceBytes = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("access_count", AccessCount);
            writer.WriteLongValue("access_count_idle_duration", AccessCountIdleDuration);
            writer.WriteStringValue("access_count_initial_time", AccessCountInitialTime);
            writer.WriteCollectionOfObjectValues<global::SnapraidDeamonApi.Models.Device>("devices", Devices);
            writer.WriteLongValue("error_data", ErrorData);
            writer.WriteLongValue("error_io", ErrorIo);
            writer.WriteLongValue("free_space_bytes", FreeSpaceBytes);
            writer.WriteEnumValue<global::SnapraidDeamonApi.Models.Disk_health>("health", Health);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::SnapraidDeamonApi.Models.Disk_power>("power", Power);
            writer.WriteCollectionOfObjectValues<global::SnapraidDeamonApi.Models.Split>("splits", Splits);
            writer.WriteLongValue("total_space_bytes", TotalSpaceBytes);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
