// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SnapraidDeamonApi.Models
{
    /// <summary>The aggregate operational health of the logical disk.* passed: All member devices are nominal, and no data  inconsistencies are detected.* corrupt: The disk has encountered silent data errors. * prefail: A critical state indicating that one or more  underlying devices have encountered I/O failures, or a  SMART prefail condition.* failing: A critical state indicating that one or more  underlying devices have encountered a SMART failing  condition.* pending: The aggregate health has not yet been  determined.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Disk_health
    {
        [EnumMember(Value = "passed")]
        #pragma warning disable CS1591
        Passed,
        #pragma warning restore CS1591
        [EnumMember(Value = "corrupt")]
        #pragma warning disable CS1591
        Corrupt,
        #pragma warning restore CS1591
        [EnumMember(Value = "prefail")]
        #pragma warning disable CS1591
        Prefail,
        #pragma warning restore CS1591
        [EnumMember(Value = "failing")]
        #pragma warning disable CS1591
        Failing,
        #pragma warning restore CS1591
        [EnumMember(Value = "pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
    }
}
