// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SnapraidDeamonApi.Models
{
    /// <summary>The logical power state of the disk, mirrored from the underlying physical device.* &apos;active&apos;: The disk is spun up. Operations like &apos;sync&apos; or &apos;scrub&apos;  on this disk will start immediately.* &apos;standby&apos;: The disk is spun down. Any array operation will  require a 10-15 second spin-up delay before data can be read.* &apos;pending&apos;: The power state is currently unknown. The daemon  is waiting for the next probe or array command to verify if  the disk is spinning.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Disk_power
    {
        [EnumMember(Value = "active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "standby")]
        #pragma warning disable CS1591
        Standby,
        #pragma warning restore CS1591
        [EnumMember(Value = "pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
    }
}
