// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SnapraidDeamonApi.Models
{
    /// <summary>Categorizes the root cause of the message. This field is **optional** and is only present for &apos;fatal&apos; and &apos;error&apos; levels: - **hardware**: Physical failures (disk Input/Output failure, silent data error). - **soft**: Logic-based anomalies (modified files during sync).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Message_type
    {
        [EnumMember(Value = "hardware")]
        #pragma warning disable CS1591
        Hardware,
        #pragma warning restore CS1591
        [EnumMember(Value = "soft")]
        #pragma warning disable CS1591
        Soft,
        #pragma warning restore CS1591
    }
}
