// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SnapraidDeamonApi.Models
{
    /// <summary>
    /// A structured log message emitted during task execution, categorized by both severity and the nature of the event.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Message : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Defines the impact on the current process: - **fatal**: Fatal error, the task stopped immediately. - **error**: Significant issue, but the task attempted to continue. - **info**: General telemetry and progress updates. - **verbose**: Verbose information.</summary>
        public global::SnapraidDeamonApi.Models.Message_level? Level { get; set; }
        /// <summary>The human-readable description of the event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>Categorizes the root cause of the message. This field is **optional** and is only present for &apos;fatal&apos; and &apos;error&apos; levels: - **hardware**: Physical failures (disk Input/Output failure, silent data error). - **soft**: Logic-based anomalies (modified files during sync).</summary>
        public global::SnapraidDeamonApi.Models.Message_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Models.Message"/> and sets the default values.
        /// </summary>
        public Message()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Models.Message"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SnapraidDeamonApi.Models.Message CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SnapraidDeamonApi.Models.Message();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "level", n => { Level = n.GetEnumValue<global::SnapraidDeamonApi.Models.Message_level>(); } },
                { "text", n => { Text = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::SnapraidDeamonApi.Models.Message_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::SnapraidDeamonApi.Models.Message_level>("level", Level);
            writer.WriteStringValue("text", Text);
            writer.WriteEnumValue<global::SnapraidDeamonApi.Models.Message_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
