// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SnapraidDeamonApi.Models
{
    /// <summary>Defines the impact on the current process: - **fatal**: Fatal error, the task stopped immediately. - **error**: Significant issue, but the task attempted to continue. - **info**: General telemetry and progress updates. - **verbose**: Verbose information.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Message_level
    {
        [EnumMember(Value = "fatal")]
        #pragma warning disable CS1591
        Fatal,
        #pragma warning restore CS1591
        [EnumMember(Value = "error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
        [EnumMember(Value = "info")]
        #pragma warning disable CS1591
        Info,
        #pragma warning restore CS1591
        [EnumMember(Value = "verbose")]
        #pragma warning disable CS1591
        Verbose,
        #pragma warning restore CS1591
    }
}
