// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SnapraidDeamonApi.Models
{
    /// <summary>
    /// A collection of monotonic sequence counters used for state change detection. Each field corresponds directly to the API entry point of the same name.If a specific pulse field increments, the corresponding endpoint will potentially return different data. Clients should use these counters to trigger selective cache invalidation.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Pulse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Related to the /activity entry point.Increments whenever the running task changes its attributes. A change here indicates that the data returned by /activity has potentially been updated.</summary>
        public long? Activity { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Related to the /array entry point.Increments when the physical state of the data array changes. A change here indicates that the data returned by /array has potentially been updated.</summary>
        public long? Array { get; set; }
        /// <summary>Related to the /config entry point.Increments when the SnapRAID Daemon configuration is altered. A change here indicates that the data returned by /config has potentially been updated.</summary>
        public long? Config { get; set; }
        /// <summary>The current local system time of the server. This acts as the master reference point for the client to synchronize its local display and calculate the relative age of other data points within the payload.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrentAt { get; set; }
#nullable restore
#else
        public string CurrentAt { get; set; }
#endif
        /// <summary>Related to the /disks entry point.Increments when the state of any disk in the array is updated. A change here indicates that the data returned by /disks has potentially been updated.</summary>
        public long? Disks { get; set; }
        /// <summary>Related to the /tasks entry point.Increments whenever any background task changes its lifecycle state. A change here indicates that the data returned by /tasks has potentially been updated.</summary>
        public long? Tasks { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Models.Pulse"/> and sets the default values.
        /// </summary>
        public Pulse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Models.Pulse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SnapraidDeamonApi.Models.Pulse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SnapraidDeamonApi.Models.Pulse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activity", n => { Activity = n.GetLongValue(); } },
                { "array", n => { Array = n.GetLongValue(); } },
                { "config", n => { Config = n.GetLongValue(); } },
                { "current_at", n => { CurrentAt = n.GetStringValue(); } },
                { "disks", n => { Disks = n.GetLongValue(); } },
                { "tasks", n => { Tasks = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("activity", Activity);
            writer.WriteLongValue("array", Array);
            writer.WriteLongValue("config", Config);
            writer.WriteStringValue("current_at", CurrentAt);
            writer.WriteLongValue("disks", Disks);
            writer.WriteLongValue("tasks", Tasks);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
