// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SnapraidDeamonApi.Models
{
    /// <summary>
    /// The root object containing the time-seriesdata and the axis limits for the scrub report.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ScrubHistory : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A sequence of data points capturingscrubbing activity at specific intervals.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SnapraidDeamonApi.Models.ScrubHistory_points>? Points { get; set; }
#nullable restore
#else
        public List<global::SnapraidDeamonApi.Models.ScrubHistory_points> Points { get; set; }
#endif
        /// <summary>The upper boundary of the X-axis,representing the most recent time.</summary>
        public int? XAxisHigh { get; set; }
        /// <summary>The lower boundary of the X-axis,representing the oldest record in the set.</summary>
        public int? XAxisLow { get; set; }
        /// <summary>The median boundary of the X-axis.</summary>
        public int? XAxisMedian { get; set; }
        /// <summary>The maximum value of the Y-axis,providing a ceiling for the vertical scale.</summary>
        public double? YAxisHigh { get; set; }
        /// <summary>The minimum value of the Y-axis,used to set the chart&apos;s vertical floor.</summary>
        public double? YAxisLow { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Models.ScrubHistory"/> and sets the default values.
        /// </summary>
        public ScrubHistory()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Models.ScrubHistory"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SnapraidDeamonApi.Models.ScrubHistory CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SnapraidDeamonApi.Models.ScrubHistory();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "points", n => { Points = n.GetCollectionOfObjectValues<global::SnapraidDeamonApi.Models.ScrubHistory_points>(global::SnapraidDeamonApi.Models.ScrubHistory_points.CreateFromDiscriminatorValue)?.AsList(); } },
                { "x_axis_high", n => { XAxisHigh = n.GetIntValue(); } },
                { "x_axis_low", n => { XAxisLow = n.GetIntValue(); } },
                { "x_axis_median", n => { XAxisMedian = n.GetIntValue(); } },
                { "y_axis_high", n => { YAxisHigh = n.GetDoubleValue(); } },
                { "y_axis_low", n => { YAxisLow = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::SnapraidDeamonApi.Models.ScrubHistory_points>("points", Points);
            writer.WriteIntValue("x_axis_high", XAxisHigh);
            writer.WriteIntValue("x_axis_low", XAxisLow);
            writer.WriteIntValue("x_axis_median", XAxisMedian);
            writer.WriteDoubleValue("y_axis_high", YAxisHigh);
            writer.WriteDoubleValue("y_axis_low", YAxisLow);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
