// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SnapraidDeamonApi.Models
{
    /// <summary>
    /// Metadata describing the host hardware and operating system environment where the daemon is executing.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class System : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The model name of the system processor, relevant for parity calculation performance.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CpuModel { get; set; }
#nullable restore
#else
        public string CpuModel { get; set; }
#endif
        /// <summary>The network name of the host machine.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Hostname { get; set; }
#nullable restore
#else
        public string Hostname { get; set; }
#endif
        /// <summary>Indicates if the system memory supports Error Correction Code (ECC), if detectable.</summary>
        public bool? IsEcc { get; set; }
        /// <summary>Currently available physical RAM.</summary>
        public long? MemoryFreeBytes { get; set; }
        /// <summary>Total physical RAM available on the host.</summary>
        public long? MemoryTotalBytes { get; set; }
        /// <summary>Manufacturer and model of the system motherboard.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Motherboard { get; set; }
#nullable restore
#else
        public string Motherboard { get; set; }
#endif
        /// <summary>The name and version of the operating system (e.g., &quot;Ubuntu 24.04 LTS&quot;).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OsDistribution { get; set; }
#nullable restore
#else
        public string OsDistribution { get; set; }
#endif
        /// <summary>The version of the running OS kernel.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OsKernelVersion { get; set; }
#nullable restore
#else
        public string OsKernelVersion { get; set; }
#endif
        /// <summary>The number of seconds the system has been running.</summary>
        public long? UptimeSeconds { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Models.System"/> and sets the default values.
        /// </summary>
        public System()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Models.System"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SnapraidDeamonApi.Models.System CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SnapraidDeamonApi.Models.System();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cpu_model", n => { CpuModel = n.GetStringValue(); } },
                { "hostname", n => { Hostname = n.GetStringValue(); } },
                { "is_ecc", n => { IsEcc = n.GetBoolValue(); } },
                { "memory_free_bytes", n => { MemoryFreeBytes = n.GetLongValue(); } },
                { "memory_total_bytes", n => { MemoryTotalBytes = n.GetLongValue(); } },
                { "motherboard", n => { Motherboard = n.GetStringValue(); } },
                { "os_distribution", n => { OsDistribution = n.GetStringValue(); } },
                { "os_kernel_version", n => { OsKernelVersion = n.GetStringValue(); } },
                { "uptime_seconds", n => { UptimeSeconds = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("cpu_model", CpuModel);
            writer.WriteStringValue("hostname", Hostname);
            writer.WriteBoolValue("is_ecc", IsEcc);
            writer.WriteLongValue("memory_free_bytes", MemoryFreeBytes);
            writer.WriteLongValue("memory_total_bytes", MemoryTotalBytes);
            writer.WriteStringValue("motherboard", Motherboard);
            writer.WriteStringValue("os_distribution", OsDistribution);
            writer.WriteStringValue("os_kernel_version", OsKernelVersion);
            writer.WriteLongValue("uptime_seconds", UptimeSeconds);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
