// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SnapraidDeamonApi.Models
{
    /// <summary>The high level command that triggered this command.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Task_high_command
    {
        [EnumMember(Value = "maintenance")]
        #pragma warning disable CS1591
        Maintenance,
        #pragma warning restore CS1591
        [EnumMember(Value = "heal")]
        #pragma warning disable CS1591
        Heal,
        #pragma warning restore CS1591
        [EnumMember(Value = "undelete")]
        #pragma warning disable CS1591
        Undelete,
        #pragma warning restore CS1591
        [EnumMember(Value = "suspend_idle")]
        #pragma warning disable CS1591
        Suspend_idle,
        #pragma warning restore CS1591
    }
}
