// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SnapraidDeamonApi.Models
{
    /// <summary>The current status of the task: queued - Waiting to be executed. starting - The task started and it&apos;s executing its initialization phase, like loading the content file. processing - The task is executing and you&apos;ll get progress information like `percentage`. finalizing - The task finished and it&apos;s doing the final phase, like saving the content file. stopping - The task received a signal, and it is performing the final phase. terminated - The task terminated, `exit_code` contains its return code. signaled - The task terminated by a signal. `exit_sig` contains its signal code. canceled - The task was never executed because a previous operation failed.  For example, a canceled scrub because the previous sync failed.  `exit_msg` contains the reason for the cancellation.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Task_status
    {
        [EnumMember(Value = "queued")]
        #pragma warning disable CS1591
        Queued,
        #pragma warning restore CS1591
        [EnumMember(Value = "starting")]
        #pragma warning disable CS1591
        Starting,
        #pragma warning restore CS1591
        [EnumMember(Value = "processing")]
        #pragma warning disable CS1591
        Processing,
        #pragma warning restore CS1591
        [EnumMember(Value = "finalizing")]
        #pragma warning disable CS1591
        Finalizing,
        #pragma warning restore CS1591
        [EnumMember(Value = "stopping")]
        #pragma warning disable CS1591
        Stopping,
        #pragma warning restore CS1591
        [EnumMember(Value = "terminated")]
        #pragma warning disable CS1591
        Terminated,
        #pragma warning restore CS1591
        [EnumMember(Value = "signaled")]
        #pragma warning disable CS1591
        Signaled,
        #pragma warning restore CS1591
        [EnumMember(Value = "canceled")]
        #pragma warning disable CS1591
        Canceled,
        #pragma warning restore CS1591
    }
}
