// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SnapraidDeamonApi.Models
{
    /// <summary>
    /// Progress status of the running or latest command. Persists until a new command begins.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TaskObject : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Starting block index.</summary>
        public long? BlockBegin { get; set; }
        /// <summary>Ending block index + 1.</summary>
        public long? BlockEnd { get; set; }
        /// <summary>Current block index position processed. Only in &apos;processing&apos;.</summary>
        public long? BlockIdx { get; set; }
        /// <summary>The number of blocks to process. It may be less than block_end - block_begin + 1 if some blocks are going to be skipped</summary>
        public long? BlocksCount { get; set; }
        /// <summary>The count of blocks processed.</summary>
        public long? BlocksDone { get; set; }
        /// <summary>The command executed.</summary>
        public global::SnapraidDeamonApi.Models.Task_command? Command { get; set; }
        /// <summary>CPU usage percentage. Only in &apos;processing&apos;.</summary>
        public int? CpuUsage { get; set; }
        /// <summary>Elapsed time in seconds. Only in &apos;processing&apos;.</summary>
        public int? ElapsedSeconds { get; set; }
        /// <summary>The count of data integrity errors encountered in the task. This tracks &apos;silent&apos; errors where a read was physically successful, but the data failed checksum verification, across the task execution. This field is available only on the `sync`, `scrub` and `fix` command.</summary>
        public long? ErrorData { get; set; }
        /// <summary>The count of physical Input/Output errors encountered in the task. This tracks hardware-level failures (disk, cable, or controller) recorded across the task execution. This field is available only on the `sync`, `scrub` and `fix` command.</summary>
        public long? ErrorIo { get; set; }
        /// <summary>The count of non-fatal logical errors encountered in the task. This tracks transient issues that do not indicate hardware or media failure, such as files being modified or removed. This field is available only on the `sync`, `scrub` and `fix` command.</summary>
        public long? ErrorSoft { get; set; }
        /// <summary>The count of errors that the `fix` command was unable to recover. If this counter is 0 it means that everything was recovered. This field is available only on the `fix` command.</summary>
        public long? ErrorUnrecoverable { get; set; }
        /// <summary>Estimated time remaining in seconds. Only in &apos;processing&apos;.</summary>
        public int? EtaSeconds { get; set; }
        /// <summary>Process exit code. Present only with status=terminated.</summary>
        public int? ExitCode { get; set; }
        /// <summary>Reason for task cancellation. Present only with status=canceled. This field describes either a failed dependency in a task sequence (e.g., sync failed so scrub was skipped) or a safety suspension (e.g., sync_threshold_deletes reached).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExitMsg { get; set; }
#nullable restore
#else
        public string ExitMsg { get; set; }
#endif
        /// <summary>Process signal code. Present only with status=signaled.</summary>
        public int? ExitSig { get; set; }
        /// <summary>The server time when the task reached a terminal state (terminated, signaled, or canceled). This timestamp is in local time.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FinishedAt { get; set; }
#nullable restore
#else
        public string FinishedAt { get; set; }
#endif
        /// <summary>The operational health of the task, dynamically derived from the execution results and exit codes.* passed: The task completed without hardware errors. This  includes runs with &apos;soft&apos; errors (e.g., files modified or moved  during execution) which do not compromise parity integrity.* corrupt: The task detected &apos;silent data errors&apos;.  This indicates data corruption that requires a heal&apos; operation,  but does not necessarily imply physical hardware failure.* prefail: The task encountered physical I/O errors. * failing: The task encountered failing errors like disks missing. * pending: The task is currently queued or running and  has not yet produced a final health result.</summary>
        public global::SnapraidDeamonApi.Models.Task_health? Health { get; set; }
        /// <summary>The high level command that triggered this command.</summary>
        public global::SnapraidDeamonApi.Models.Task_high_command? HighCommand { get; set; }
        /// <summary>The absolute path to the log file for this specific task execution. This file is stored in the directory defined by &apos;sys_log_directory&apos; in the config.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LogFile { get; set; }
#nullable restore
#else
        public string LogFile { get; set; }
#endif
        /// <summary>A chronological collection of messages generated during this task&apos;s execution.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SnapraidDeamonApi.Models.Message>? Messages { get; set; }
#nullable restore
#else
        public List<global::SnapraidDeamonApi.Models.Message> Messages { get; set; }
#endif
        /// <summary>The incremental number of task. It can be used to identify tasks when moved from queue to process to history.</summary>
        public int? Number { get; set; }
        /// <summary>Completion percentage. Only in &apos;processing&apos;.</summary>
        public int? Progress { get; set; }
        /// <summary>The complete text-based results of a &apos;report&apos; type tasks.For high-level maintenance macros (such as &apos;maintenance&apos;, &apos;heal&apos;, or &apos;undelete&apos;), the daemon automatically appends a final &apos;report&apos; command to the task sequence upon successful completion of the primary actions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReportOutput { get; set; }
#nullable restore
#else
        public string ReportOutput { get; set; }
#endif
        /// <summary>The time when the task was added to the queue. This timestamp is in local time.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScheduledAt { get; set; }
#nullable restore
#else
        public string ScheduledAt { get; set; }
#endif
        /// <summary>Size of blocks processed.</summary>
        public long? SizeDoneBytes { get; set; }
        /// <summary>Realtime speed in Mbytes/s. Only in &apos;processing&apos;.</summary>
        public int? SpeedMbs { get; set; }
        /// <summary>The server time when the task moved from &apos;queued&apos; to &apos;starting&apos;. This timestamp is in local time.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartedAt { get; set; }
#nullable restore
#else
        public string StartedAt { get; set; }
#endif
        /// <summary>The current status of the task: queued - Waiting to be executed. starting - The task started and it&apos;s executing its initialization phase, like loading the content file. processing - The task is executing and you&apos;ll get progress information like `percentage`. finalizing - The task finished and it&apos;s doing the final phase, like saving the content file. stopping - The task received a signal, and it is performing the final phase. terminated - The task terminated, `exit_code` contains its return code. signaled - The task terminated by a signal. `exit_sig` contains its signal code. canceled - The task was never executed because a previous operation failed.  For example, a canceled scrub because the previous sync failed.  `exit_msg` contains the reason for the cancellation.</summary>
        public global::SnapraidDeamonApi.Models.Task_status? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Models.TaskObject"/> and sets the default values.
        /// </summary>
        public TaskObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Models.TaskObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SnapraidDeamonApi.Models.TaskObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SnapraidDeamonApi.Models.TaskObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "block_begin", n => { BlockBegin = n.GetLongValue(); } },
                { "block_end", n => { BlockEnd = n.GetLongValue(); } },
                { "block_idx", n => { BlockIdx = n.GetLongValue(); } },
                { "blocks_count", n => { BlocksCount = n.GetLongValue(); } },
                { "blocks_done", n => { BlocksDone = n.GetLongValue(); } },
                { "command", n => { Command = n.GetEnumValue<global::SnapraidDeamonApi.Models.Task_command>(); } },
                { "cpu_usage", n => { CpuUsage = n.GetIntValue(); } },
                { "elapsed_seconds", n => { ElapsedSeconds = n.GetIntValue(); } },
                { "error_data", n => { ErrorData = n.GetLongValue(); } },
                { "error_io", n => { ErrorIo = n.GetLongValue(); } },
                { "error_soft", n => { ErrorSoft = n.GetLongValue(); } },
                { "error_unrecoverable", n => { ErrorUnrecoverable = n.GetLongValue(); } },
                { "eta_seconds", n => { EtaSeconds = n.GetIntValue(); } },
                { "exit_code", n => { ExitCode = n.GetIntValue(); } },
                { "exit_msg", n => { ExitMsg = n.GetStringValue(); } },
                { "exit_sig", n => { ExitSig = n.GetIntValue(); } },
                { "finished_at", n => { FinishedAt = n.GetStringValue(); } },
                { "health", n => { Health = n.GetEnumValue<global::SnapraidDeamonApi.Models.Task_health>(); } },
                { "high_command", n => { HighCommand = n.GetEnumValue<global::SnapraidDeamonApi.Models.Task_high_command>(); } },
                { "log_file", n => { LogFile = n.GetStringValue(); } },
                { "messages", n => { Messages = n.GetCollectionOfObjectValues<global::SnapraidDeamonApi.Models.Message>(global::SnapraidDeamonApi.Models.Message.CreateFromDiscriminatorValue)?.AsList(); } },
                { "number", n => { Number = n.GetIntValue(); } },
                { "progress", n => { Progress = n.GetIntValue(); } },
                { "report_output", n => { ReportOutput = n.GetStringValue(); } },
                { "scheduled_at", n => { ScheduledAt = n.GetStringValue(); } },
                { "size_done_bytes", n => { SizeDoneBytes = n.GetLongValue(); } },
                { "speed_mbs", n => { SpeedMbs = n.GetIntValue(); } },
                { "started_at", n => { StartedAt = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::SnapraidDeamonApi.Models.Task_status>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("block_begin", BlockBegin);
            writer.WriteLongValue("block_end", BlockEnd);
            writer.WriteLongValue("block_idx", BlockIdx);
            writer.WriteLongValue("blocks_count", BlocksCount);
            writer.WriteLongValue("blocks_done", BlocksDone);
            writer.WriteEnumValue<global::SnapraidDeamonApi.Models.Task_command>("command", Command);
            writer.WriteIntValue("cpu_usage", CpuUsage);
            writer.WriteIntValue("elapsed_seconds", ElapsedSeconds);
            writer.WriteLongValue("error_data", ErrorData);
            writer.WriteLongValue("error_io", ErrorIo);
            writer.WriteLongValue("error_soft", ErrorSoft);
            writer.WriteLongValue("error_unrecoverable", ErrorUnrecoverable);
            writer.WriteIntValue("eta_seconds", EtaSeconds);
            writer.WriteIntValue("exit_code", ExitCode);
            writer.WriteStringValue("exit_msg", ExitMsg);
            writer.WriteIntValue("exit_sig", ExitSig);
            writer.WriteStringValue("finished_at", FinishedAt);
            writer.WriteEnumValue<global::SnapraidDeamonApi.Models.Task_health>("health", Health);
            writer.WriteEnumValue<global::SnapraidDeamonApi.Models.Task_high_command>("high_command", HighCommand);
            writer.WriteStringValue("log_file", LogFile);
            writer.WriteCollectionOfObjectValues<global::SnapraidDeamonApi.Models.Message>("messages", Messages);
            writer.WriteIntValue("number", Number);
            writer.WriteIntValue("progress", Progress);
            writer.WriteStringValue("report_output", ReportOutput);
            writer.WriteStringValue("scheduled_at", ScheduledAt);
            writer.WriteLongValue("size_done_bytes", SizeDoneBytes);
            writer.WriteIntValue("speed_mbs", SpeedMbs);
            writer.WriteStringValue("started_at", StartedAt);
            writer.WriteEnumValue<global::SnapraidDeamonApi.Models.Task_status>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
