// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SnapraidDeamonApi.Models
{
    /// <summary>The operational health of the task, dynamically derived from the execution results and exit codes.* passed: The task completed without hardware errors. This  includes runs with &apos;soft&apos; errors (e.g., files modified or moved  during execution) which do not compromise parity integrity.* corrupt: The task detected &apos;silent data errors&apos;.  This indicates data corruption that requires a heal&apos; operation,  but does not necessarily imply physical hardware failure.* prefail: The task encountered physical I/O errors. * failing: The task encountered failing errors like disks missing. * pending: The task is currently queued or running and  has not yet produced a final health result.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Task_health
    {
        [EnumMember(Value = "passed")]
        #pragma warning disable CS1591
        Passed,
        #pragma warning restore CS1591
        [EnumMember(Value = "corrupt")]
        #pragma warning disable CS1591
        Corrupt,
        #pragma warning restore CS1591
        [EnumMember(Value = "prefail")]
        #pragma warning disable CS1591
        Prefail,
        #pragma warning restore CS1591
        [EnumMember(Value = "failing")]
        #pragma warning disable CS1591
        Failing,
        #pragma warning restore CS1591
        [EnumMember(Value = "pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
    }
}
