// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SnapraidDeamonApi.Models
{
    /// <summary>
    /// Historical metadata and change tracking for a parent value. The entire object is omitted if the value has never changed since the daemon started.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ValueHistory : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The historical minimum value observed by the daemon.</summary>
        public long? Lowest { get; set; }
        /// <summary>The timestamp of the most recent occurrence where the value reached the &apos;lowest&apos; record.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LowestAt { get; set; }
#nullable restore
#else
        public string LowestAt { get; set; }
#endif
        /// <summary>The immediate previous value held before the latest change.</summary>
        public long? Prev { get; set; }
        /// <summary>The timestamp when the value transitioned from &apos;prev&apos; to the current value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrevAt { get; set; }
#nullable restore
#else
        public string PrevAt { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Models.ValueHistory"/> and sets the default values.
        /// </summary>
        public ValueHistory()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Models.ValueHistory"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SnapraidDeamonApi.Models.ValueHistory CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SnapraidDeamonApi.Models.ValueHistory();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "lowest", n => { Lowest = n.GetLongValue(); } },
                { "lowest_at", n => { LowestAt = n.GetStringValue(); } },
                { "prev", n => { Prev = n.GetLongValue(); } },
                { "prev_at", n => { PrevAt = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("lowest", Lowest);
            writer.WriteStringValue("lowest_at", LowestAt);
            writer.WriteLongValue("prev", Prev);
            writer.WriteStringValue("prev_at", PrevAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
