// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using SnapraidDeamonApi.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SnapraidDeamonApi.Snapraid.V1.Config
{
    /// <summary>
    /// Builds and executes requests for operations under \snapraid\v1\config
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConfigRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Snapraid.V1.Config.ConfigRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConfigRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/snapraid/v1/config", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Snapraid.V1.Config.ConfigRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConfigRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/snapraid/v1/config", rawUrl)
        {
        }
        /// <summary>
        /// Returns the current operational parameters of the daemon. This includes settings parsed from &apos;snapraidd.conf&apos; as well as any overrides applied during the current session.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.Config.ConfigGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::SnapraidDeamonApi.Models.Config400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Config405Error">When receiving a 405 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Config.ConfigGetResponse?> GetAsConfigGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Config.ConfigGetResponse> GetAsConfigGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::SnapraidDeamonApi.Models.Config400Error.CreateFromDiscriminatorValue },
                { "405", global::SnapraidDeamonApi.Models.Config405Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::SnapraidDeamonApi.Snapraid.V1.Config.ConfigGetResponse>(requestInfo, global::SnapraidDeamonApi.Snapraid.V1.Config.ConfigGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the current operational parameters of the daemon. This includes settings parsed from &apos;snapraidd.conf&apos; as well as any overrides applied during the current session.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.Config.ConfigResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::SnapraidDeamonApi.Models.Config400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Config405Error">When receiving a 405 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsConfigGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Config.ConfigResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Config.ConfigResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::SnapraidDeamonApi.Models.Config400Error.CreateFromDiscriminatorValue },
                { "405", global::SnapraidDeamonApi.Models.Config405Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::SnapraidDeamonApi.Snapraid.V1.Config.ConfigResponse>(requestInfo, global::SnapraidDeamonApi.Snapraid.V1.Config.ConfigResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Performs a partial update of the daemon settings. Validated changes are immediately applied to the running process and persisted to the &apos;snapraidd.conf&apos; file on disk.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.Config.ConfigPatchResponse"/></returns>
        /// <param name="body">Global configuration state for the SnapRAID Daemon.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::SnapraidDeamonApi.Models.Config400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Config403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Config405Error">When receiving a 405 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Config.ConfigPatchResponse?> PatchAsConfigPatchResponseAsync(global::SnapraidDeamonApi.Models.Config body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Config.ConfigPatchResponse> PatchAsConfigPatchResponseAsync(global::SnapraidDeamonApi.Models.Config body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::SnapraidDeamonApi.Models.Config400Error.CreateFromDiscriminatorValue },
                { "403", global::SnapraidDeamonApi.Models.Config403Error.CreateFromDiscriminatorValue },
                { "405", global::SnapraidDeamonApi.Models.Config405Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::SnapraidDeamonApi.Snapraid.V1.Config.ConfigPatchResponse>(requestInfo, global::SnapraidDeamonApi.Snapraid.V1.Config.ConfigPatchResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Performs a partial update of the daemon settings. Validated changes are immediately applied to the running process and persisted to the &apos;snapraidd.conf&apos; file on disk.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.Config.ConfigResponse"/></returns>
        /// <param name="body">Global configuration state for the SnapRAID Daemon.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::SnapraidDeamonApi.Models.Config400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Config403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Config405Error">When receiving a 405 status code</exception>
        [Obsolete("This method is obsolete. Use PatchAsConfigPatchResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Config.ConfigResponse?> PatchAsync(global::SnapraidDeamonApi.Models.Config body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Config.ConfigResponse> PatchAsync(global::SnapraidDeamonApi.Models.Config body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::SnapraidDeamonApi.Models.Config400Error.CreateFromDiscriminatorValue },
                { "403", global::SnapraidDeamonApi.Models.Config403Error.CreateFromDiscriminatorValue },
                { "405", global::SnapraidDeamonApi.Models.Config405Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::SnapraidDeamonApi.Snapraid.V1.Config.ConfigResponse>(requestInfo, global::SnapraidDeamonApi.Snapraid.V1.Config.ConfigResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the current operational parameters of the daemon. This includes settings parsed from &apos;snapraidd.conf&apos; as well as any overrides applied during the current session.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Performs a partial update of the daemon settings. Validated changes are immediately applied to the running process and persisted to the &apos;snapraidd.conf&apos; file on disk.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Global configuration state for the SnapRAID Daemon.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::SnapraidDeamonApi.Models.Config body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::SnapraidDeamonApi.Models.Config body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.Config.ConfigRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::SnapraidDeamonApi.Snapraid.V1.Config.ConfigRequestBuilder WithUrl(string rawUrl)
        {
            return new global::SnapraidDeamonApi.Snapraid.V1.Config.ConfigRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ConfigRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ConfigRequestBuilderPatchRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
