// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using SnapraidDeamonApi.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SnapraidDeamonApi.Snapraid.V1.Refresh
{
    /// <summary>
    /// Builds and executes requests for operations under \snapraid\v1\refresh
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RefreshRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Snapraid.V1.Refresh.RefreshRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RefreshRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/snapraid/v1/refresh", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Snapraid.V1.Refresh.RefreshRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RefreshRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/snapraid/v1/refresh", rawUrl)
        {
        }
        /// <summary>
        /// Forces the daemon to re-synchronize its internal state with the content file. This is intended for use after manual interventions performed outside the daemon interface (e.g., replacing a failed disk, fixing UUID mismatches, or manually updating configuration).The operation executes a &apos;read&apos; task to load the current content file data, followed by a &apos;report&apos; task to evaluate and broadcast the resulting array health.This is specifically useful for clearing &apos;FAILING&apos; or &apos;PREFAIL&apos; modes once the underlying hardware or configuration issues have been resolved manually.This is an asynchronous operation. Monitor progress via the /activity endpoint.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.Refresh.RefreshPostResponse"/></returns>
        /// <param name="body">Optional configuration for the task.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::SnapraidDeamonApi.Models.Refresh400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Refresh405Error">When receiving a 405 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Refresh500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Refresh.RefreshPostResponse?> PostAsRefreshPostResponseAsync(global::SnapraidDeamonApi.Models.CommandRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Refresh.RefreshPostResponse> PostAsRefreshPostResponseAsync(global::SnapraidDeamonApi.Models.CommandRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::SnapraidDeamonApi.Models.Refresh400Error.CreateFromDiscriminatorValue },
                { "405", global::SnapraidDeamonApi.Models.Refresh405Error.CreateFromDiscriminatorValue },
                { "500", global::SnapraidDeamonApi.Models.Refresh500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::SnapraidDeamonApi.Snapraid.V1.Refresh.RefreshPostResponse>(requestInfo, global::SnapraidDeamonApi.Snapraid.V1.Refresh.RefreshPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Forces the daemon to re-synchronize its internal state with the content file. This is intended for use after manual interventions performed outside the daemon interface (e.g., replacing a failed disk, fixing UUID mismatches, or manually updating configuration).The operation executes a &apos;read&apos; task to load the current content file data, followed by a &apos;report&apos; task to evaluate and broadcast the resulting array health.This is specifically useful for clearing &apos;FAILING&apos; or &apos;PREFAIL&apos; modes once the underlying hardware or configuration issues have been resolved manually.This is an asynchronous operation. Monitor progress via the /activity endpoint.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.Refresh.RefreshResponse"/></returns>
        /// <param name="body">Optional configuration for the task.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::SnapraidDeamonApi.Models.Refresh400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Refresh405Error">When receiving a 405 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Refresh500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsRefreshPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Refresh.RefreshResponse?> PostAsync(global::SnapraidDeamonApi.Models.CommandRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Refresh.RefreshResponse> PostAsync(global::SnapraidDeamonApi.Models.CommandRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::SnapraidDeamonApi.Models.Refresh400Error.CreateFromDiscriminatorValue },
                { "405", global::SnapraidDeamonApi.Models.Refresh405Error.CreateFromDiscriminatorValue },
                { "500", global::SnapraidDeamonApi.Models.Refresh500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::SnapraidDeamonApi.Snapraid.V1.Refresh.RefreshResponse>(requestInfo, global::SnapraidDeamonApi.Snapraid.V1.Refresh.RefreshResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Forces the daemon to re-synchronize its internal state with the content file. This is intended for use after manual interventions performed outside the daemon interface (e.g., replacing a failed disk, fixing UUID mismatches, or manually updating configuration).The operation executes a &apos;read&apos; task to load the current content file data, followed by a &apos;report&apos; task to evaluate and broadcast the resulting array health.This is specifically useful for clearing &apos;FAILING&apos; or &apos;PREFAIL&apos; modes once the underlying hardware or configuration issues have been resolved manually.This is an asynchronous operation. Monitor progress via the /activity endpoint.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Optional configuration for the task.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::SnapraidDeamonApi.Models.CommandRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::SnapraidDeamonApi.Models.CommandRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.Refresh.RefreshRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::SnapraidDeamonApi.Snapraid.V1.Refresh.RefreshRequestBuilder WithUrl(string rawUrl)
        {
            return new global::SnapraidDeamonApi.Snapraid.V1.Refresh.RefreshRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RefreshRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
