// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using SnapraidDeamonApi.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SnapraidDeamonApi.Snapraid.V1.Hold_off
{
    /// <summary>
    /// Builds and executes requests for operations under \snapraid\v1\hold_off
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Hold_offRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Snapraid.V1.Hold_off.Hold_offRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Hold_offRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/snapraid/v1/hold_off", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SnapraidDeamonApi.Snapraid.V1.Hold_off.Hold_offRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Hold_offRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/snapraid/v1/hold_off", rawUrl)
        {
        }
        /// <summary>
        /// Controls the one-shot skip state for the next scheduled maintenance task. If enabled, the immediate next scheduled maintenance window is bypassed. The system will automatically reset this state to disabled once a scheduled task has been skipped.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.Hold_off.Hold_offPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::SnapraidDeamonApi.Models.Hold_off400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Hold_off405Error">When receiving a 405 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Hold_off.Hold_offPostResponse?> PostAsHold_offPostResponseAsync(global::SnapraidDeamonApi.Snapraid.V1.Hold_off.Hold_offPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Hold_off.Hold_offPostResponse> PostAsHold_offPostResponseAsync(global::SnapraidDeamonApi.Snapraid.V1.Hold_off.Hold_offPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::SnapraidDeamonApi.Models.Hold_off400Error.CreateFromDiscriminatorValue },
                { "405", global::SnapraidDeamonApi.Models.Hold_off405Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::SnapraidDeamonApi.Snapraid.V1.Hold_off.Hold_offPostResponse>(requestInfo, global::SnapraidDeamonApi.Snapraid.V1.Hold_off.Hold_offPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Controls the one-shot skip state for the next scheduled maintenance task. If enabled, the immediate next scheduled maintenance window is bypassed. The system will automatically reset this state to disabled once a scheduled task has been skipped.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.Hold_off.Hold_offResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::SnapraidDeamonApi.Models.Hold_off400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::SnapraidDeamonApi.Models.Hold_off405Error">When receiving a 405 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsHold_offPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Hold_off.Hold_offResponse?> PostAsync(global::SnapraidDeamonApi.Snapraid.V1.Hold_off.Hold_offPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SnapraidDeamonApi.Snapraid.V1.Hold_off.Hold_offResponse> PostAsync(global::SnapraidDeamonApi.Snapraid.V1.Hold_off.Hold_offPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::SnapraidDeamonApi.Models.Hold_off400Error.CreateFromDiscriminatorValue },
                { "405", global::SnapraidDeamonApi.Models.Hold_off405Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::SnapraidDeamonApi.Snapraid.V1.Hold_off.Hold_offResponse>(requestInfo, global::SnapraidDeamonApi.Snapraid.V1.Hold_off.Hold_offResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Controls the one-shot skip state for the next scheduled maintenance task. If enabled, the immediate next scheduled maintenance window is bypassed. The system will automatically reset this state to disabled once a scheduled task has been skipped.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::SnapraidDeamonApi.Snapraid.V1.Hold_off.Hold_offPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::SnapraidDeamonApi.Snapraid.V1.Hold_off.Hold_offPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::SnapraidDeamonApi.Snapraid.V1.Hold_off.Hold_offRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::SnapraidDeamonApi.Snapraid.V1.Hold_off.Hold_offRequestBuilder WithUrl(string rawUrl)
        {
            return new global::SnapraidDeamonApi.Snapraid.V1.Hold_off.Hold_offRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Hold_offRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
